//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef anab__Calorimetry_h
#define anab__Calorimetry_h
namespace anab {
class Calorimetry;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "TVector3.h"
#include "geo__PlaneID.h"

namespace anab {
class Calorimetry {

public:
// Nested classes declaration.

public:
// Data Members.
   double      fKineticEnergy;    //determined kinetic energy
   vector<double> fdEdx;             //dE/dx, should be same size as fResidualRange
   vector<double> fdQdx;             //dQ/dx
   vector<double> fResidualRange;    //range from end of track
   vector<double> fDeadWireResR;     //dead wire residual range, collection plane
   double         fRange;            //total range of track
   vector<double> fTrkPitch;         //track pitch on collection plane
   vector<TVector3> fXYZ;              //coordinates of space points
   geo::PlaneID     fPlaneID;          //

   Calorimetry();
   Calorimetry(const Calorimetry & );
   virtual ~Calorimetry();

   ClassDef(Calorimetry,17); // Generated by MakeProject.
};
} // namespace
#endif
