//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__FileFormatVersion_h
#define art__FileFormatVersion_h
namespace art {
class FileFormatVersion;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace art {
class FileFormatVersion {

public:
// Nested classes declaration.

public:
// Data Members.
   int         value_;      //
   string      era_;        //

   FileFormatVersion();
   FileFormatVersion(const FileFormatVersion & );
   virtual ~FileFormatVersion();

   ClassDef(FileFormatVersion,11); // Generated by MakeProject.
};
} // namespace
#endif
