//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__HLTGlobalStatus_h
#define art__HLTGlobalStatus_h
namespace art {
class HLTGlobalStatus;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "art__HLTPathStatus.h"

namespace art {
class HLTGlobalStatus {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<art::HLTPathStatus> paths_;      //

   HLTGlobalStatus();
   HLTGlobalStatus(const HLTGlobalStatus & );
   virtual ~HLTGlobalStatus();

   ClassDef(HLTGlobalStatus,11); // Generated by MakeProject.
};
} // namespace
#endif
