//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__RunAuxiliary_h
#define art__RunAuxiliary_h
namespace art {
class RunAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__Hash_2_.h"
#include "Riostream.h"
#include <set>
#include "art__RunID.h"
#include "art__Timestamp.h"

namespace art {
class RunAuxiliary {

public:
// Nested classes declaration.

public:
// Data Members.
   art::Hash<2> processHistoryID_;    //
   std::vector<art::Hash<2> > allEventsProcessHistories_;    //
   unsigned int               rangeSetID_;                   //
   art::RunID                 id_;                           //
   art::Timestamp             beginTime_;                    //
   art::Timestamp             endTime_;                      //

   RunAuxiliary();
   RunAuxiliary(const RunAuxiliary & );
   virtual ~RunAuxiliary();

   ClassDef(RunAuxiliary,12); // Generated by MakeProject.
};
} // namespace
#endif
