//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__Wrapper_vector_larpandoraobj__PFParticleMetadata____h
#define art__Wrapper_vector_larpandoraobj__PFParticleMetadata____h
#include <vector>
namespace std {} using namespace std;
namespace larpandoraobj {
class PFParticleMetadata;
} // end of namespace.
namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<vector<larpandoraobj::PFParticleMetadata> >;
} // end of namespace.

namespace std {} using namespace std;
#include "larpandoraobj__PFParticleMetadata.h"
#include "art__EDProduct.h"
#include "Riostream.h"

namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<vector<larpandoraobj::PFParticleMetadata> > : public art::EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   unsigned int rangeSetID;    //
   vector<larpandoraobj::PFParticleMetadata> obj;           // (larpandoraobj::PFParticleMetadata)

   Wrapper();
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,12); // Generated by MakeProject.
};
} // namespace
#endif
