//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__ProductID_h
#define art__ProductID_h
namespace art {
class ProductID;
} // end of namespace.

#include "Rtypes.h"

namespace art {
class ProductID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int value_;      //

   ProductID();
   ProductID(const ProductID & );
   virtual ~ProductID();

   ClassDef(ProductID,11); // Generated by MakeProject.
};
} // namespace
#endif
