//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__EDProduct_h
#define art__EDProduct_h
namespace art {
class EDProduct;
} // end of namespace.

#include "Rtypes.h"

namespace art {
class EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.

   EDProduct();
   EDProduct(const EDProduct & );
   virtual ~EDProduct();

   ClassDef(EDProduct,11); // Generated by MakeProject.
};
} // namespace
#endif
