//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__RefCore_h
#define art__RefCore_h
namespace art {
class RefCore;
} // end of namespace.

#include "Rtypes.h"
#include "art__ProductID.h"
#include "art__RefCore.h"

namespace art {
class RefCore {

public:
// Nested classes forward declaration.
class RefCoreTransients;

public:
// Nested classes declaration.
class RefCoreTransients {

public:
// Nested classes declaration.

public:
// Data Members.

   RefCoreTransients();
   RefCoreTransients(const RefCoreTransients & );
   virtual ~RefCoreTransients();

   ClassDef(RefCoreTransients,11); // Generated by MakeProject.
};

public:
// Data Members.
   art::ProductID id_;         //
   art::RefCore::RefCoreTransients transients_;    //

   RefCore();
   RefCore(const RefCore & );
   virtual ~RefCore();

   ClassDef(RefCore,11); // Generated by MakeProject.
};
} // namespace
#endif
