//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__ProductProvenance_h
#define art__ProductProvenance_h
namespace art {
class ProductProvenance;
} // end of namespace.

#include "Rtypes.h"
#include "art__ProductID.h"
#include "art__Hash_5_.h"
#include "art__Transient_art__ProductProvenance__Transients_.h"
namespace art {
#ifndef art__ProductProvenance_h
#define art__ProductProvenance_h
enum ProductProvenance::Transients { kDefault_ProductProvenance::Transients };
#endif
} // end of namespace.

namespace art {
class ProductProvenance {

public:
// Nested classes forward declaration.
enum Transients { kDefault_Transients };

public:
// Nested classes declaration.

public:
// Data Members.
   art::ProductID productID_;    //
   unsigned char  productStatus_;    //
   art::Hash<5>   parentageID_;      //
   art::Transient<art::ProductProvenance::Transients> transients_;       //

   ProductProvenance();
   ProductProvenance(const ProductProvenance & );
   virtual ~ProductProvenance();

   ClassDef(ProductProvenance,12); // Generated by MakeProject.
};
} // namespace
#endif
