//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__Assns_recob__Cluster_recob__Vertex_unsigned_short__h
#define art__Assns_recob__Cluster_recob__Vertex_unsigned_short__h
namespace recob {
class Cluster;
} // end of namespace.
namespace recob {
class Vertex;
} // end of namespace.
namespace art {
template <typename T0, typename T1, typename T2> class Assns;
template <> class Assns<recob::Cluster,recob::Vertex,unsigned short>;
} // end of namespace.

#include "Rtypes.h"
#include "recob__Cluster.h"
#include "recob__Vertex.h"
#include "art__Assns_recob__Cluster_recob__Vertex_void_.h"
#include "Riostream.h"
#include <vector>

namespace art {
template <typename T0, typename T1, typename T2> class Assns;
template <> class Assns<recob::Cluster,recob::Vertex,unsigned short> : public art::Assns<recob::Cluster,recob::Vertex,void> {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<unsigned short> data_;       //

   Assns();
   Assns(const Assns & );
   virtual ~Assns();

   ClassDef(Assns,12); // Generated by MakeProject.
};
} // namespace
#endif
