//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef art__History_h
#define art__History_h
namespace art {
class History;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "fhicl__ParameterSetID.h"
#include "art__Hash_2_.h"

namespace art {
class History {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<fhicl::ParameterSetID> eventSelections_;    //
   vector<unsigned short>        branchListIndexes_;    //
   art::Hash<2>                  processHistoryID_;     //

   History();
   History(const History & );
   virtual ~History();

   ClassDef(History,11); // Generated by MakeProject.
};
} // namespace
#endif
