//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef artdaq__Fragment_h
#define artdaq__Fragment_h
namespace artdaq {
class Fragment;
} // end of namespace.

#include "Rtypes.h"
#include "artdaq__QuickVec_ULong64_t_.h"

namespace artdaq {
class Fragment {

public:
// Nested classes declaration.

public:
// Data Members.
   artdaq::QuickVec<ULong64_t> vals_;       //

   Fragment();
   Fragment(const Fragment & );
   virtual ~Fragment();

   ClassDef(Fragment,16); // Generated by MakeProject.
};
} // namespace
#endif
