//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef artdaq__QuickVec_ULong64_t__h
#define artdaq__QuickVec_ULong64_t__h
namespace artdaq {
template <typename T0> class QuickVec;
template <> class QuickVec<ULong64_t>;
} // end of namespace.

#include "Rtypes.h"

namespace artdaq {
template <typename T0> class QuickVec;
template <> class QuickVec<ULong64_t> {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int size_;       //
   ULong64_t*   data_;       //[size_]
   unsigned int capacity_;    //

   QuickVec();
   QuickVec(const QuickVec & );
   virtual ~QuickVec();

   ClassDef(QuickVec,6); // Generated by MakeProject.
};
} // namespace
#endif
