//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef artdaq__PackageBuildInfo_h
#define artdaq__PackageBuildInfo_h
namespace artdaq {
class PackageBuildInfo;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace artdaq {
class PackageBuildInfo {

public:
// Nested classes declaration.

public:
// Data Members.
   string      packageName_;    //
   string      packageVersion_;    //
   string      buildTimestamp_;    //

   PackageBuildInfo();
   PackageBuildInfo(const PackageBuildInfo & );
   virtual ~PackageBuildInfo();

   ClassDef(PackageBuildInfo,12); // Generated by MakeProject.
};
} // namespace
#endif
