//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef dune__ProtoDUNETimeStamp_h
#define dune__ProtoDUNETimeStamp_h
namespace dune {
class ProtoDUNETimeStamp;
} // end of namespace.

#include "Rtypes.h"

namespace dune {
class ProtoDUNETimeStamp {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int m_cookie;    //
   Int_t        m_triggerType;    //
   unsigned int m_reservedBits;    //
   ULong64_t    m_timeStamp;       //
   unsigned int m_eventCounter;    //
   bool         m_checksumGood;    //
   ULong64_t    m_lastRunStart;    //
   ULong64_t    m_lastSpillStart;    //
   ULong64_t    m_lastSpillEnd;      //
   unsigned int m_version;           //

   ProtoDUNETimeStamp();
   ProtoDUNETimeStamp(const ProtoDUNETimeStamp & );
   virtual ~ProtoDUNETimeStamp();

};
} // namespace
#endif
