//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef geo__TPCID_h
#define geo__TPCID_h
namespace geo {
class TPCID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__CryostatID.h"

namespace geo {
class TPCID : public geo::CryostatID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int TPC;         //Index of the TPC within its cryostat.

   TPCID();
   TPCID(const TPCID & );
   virtual ~TPCID();

   ClassDef(TPCID,19); // Generated by MakeProject.
};
} // namespace
#endif
