//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef geo__PlaneID_h
#define geo__PlaneID_h
namespace geo {
class PlaneID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__TPCID.h"

namespace geo {
class PlaneID : public geo::TPCID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int Plane;       //Index of the plane within its TPC.

   PlaneID();
   PlaneID(const PlaneID & );
   virtual ~PlaneID();

   ClassDef(PlaneID,4); // Generated by MakeProject.
};
} // namespace
#endif
