//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef lar__range_t_unsigned_long__h
#define lar__range_t_unsigned_long__h
namespace lar {
template <typename T0> class range_t;
template <> class range_t<unsigned long>;
} // end of namespace.

#include "Rtypes.h"

namespace lar {
template <typename T0> class range_t;
template <> class range_t<unsigned long> {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long offset;      //offset (absolute index) of the first element
   unsigned long last;        //offset (absolute index) after the last element

   range_t();
   range_t(const range_t & );
   virtual ~range_t();

};
} // namespace
#endif
