//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef larpandoraobj__PFParticleMetadata_h
#define larpandoraobj__PFParticleMetadata_h
namespace larpandoraobj {
class PFParticleMetadata;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <map>

namespace larpandoraobj {
class PFParticleMetadata {

public:
// Nested classes declaration.

public:
// Data Members.
//   std::vector<std::pair<std::string,float> > m_propertiesMap;    //The properties map
   std::map<std::string,float > m_propertiesMap;    //The properties map
   
   PFParticleMetadata();
   PFParticleMetadata(const PFParticleMetadata & );
   virtual ~PFParticleMetadata();

};
} // namespace
#endif
