//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef raw__ctb__WordIndex_h
#define raw__ctb__WordIndex_h
namespace raw {
namespace ctb {
class WordIndex;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"

namespace raw {
namespace ctb {
class WordIndex {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int word_type;    //
   unsigned int index;        //

   WordIndex();
   WordIndex(const WordIndex & );
   virtual ~WordIndex();

   ClassDef(WordIndex,11); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
