//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef raw__OpDetWaveform_h
#define raw__OpDetWaveform_h
namespace raw {
class OpDetWaveform;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace raw {
class OpDetWaveform : public vector<short> {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fChannel;    //
   double       fTimeStamp;    //

   OpDetWaveform();
   OpDetWaveform(const OpDetWaveform & );
   virtual ~OpDetWaveform();

   ClassDef(OpDetWaveform,14); // Generated by MakeProject.
};
} // namespace
#endif
