//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef raw__RDStatus_h
#define raw__RDStatus_h
namespace raw {
class RDStatus;
} // end of namespace.

#include "Rtypes.h"

namespace raw {
class RDStatus {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        fCorruptDataDropped;    //True if some data suspected to be corrupt were not decoded
   bool        fCorruptDataKept;       //True if some data suspected to be corrupt were decoded
   unsigned int fStatWord;              //

   RDStatus();
   RDStatus(const RDStatus & );
   virtual ~RDStatus();

   ClassDef(RDStatus,11); // Generated by MakeProject.
};
} // namespace
#endif
