//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef recob__PFParticle_h
#define recob__PFParticle_h
namespace recob {
class PFParticle;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace recob {
class PFParticle {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fPdgCode;    //A preliminary estimate of the PFParticle type using the PDG code
   unsigned long fSelf;       //Self reference
   unsigned long fParent;     //Index into PFParticle collection for parent
   vector<unsigned long> fDaughters;    //Vector of indices into PFParticle Collection for daughters

   PFParticle();
   PFParticle(const PFParticle & );
   virtual ~PFParticle();

   ClassDef(PFParticle,14); // Generated by MakeProject.
};
} // namespace
#endif
