//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef recob__Shower_h
#define recob__Shower_h
namespace recob {
class Shower;
} // end of namespace.

#include "Rtypes.h"
#include "TVector3.h"
#include "Riostream.h"
#include <vector>

namespace recob {
class Shower {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fID;         //
   TVector3    fDCosStart;    //direction cosines at start of shower
   TVector3    fSigmaDCosStart;    //uncertainty on initial direction cosines
   TVector3    fXYZstart;          //direction cosines at start of shower
   TVector3    fSigmaXYZstart;     //uncertainty on initial direction cosines
   vector<double> fTotalEnergy;       //Calculated Energy per each plane
   vector<double> fSigmaTotalEnergy;    //Calculated Energy per each plane
   vector<double> fdEdx;                //Calculated dE/dx per each plane
   vector<double> fSigmadEdx;           //Calculated dE/dx per each plane
   vector<double> fTotalMIPEnergy;      //Calculated Energy per each plane
   vector<double> fSigmaTotalMIPEnergy;    //Calculated Energy per each plane
   int            fBestPlane;              //
   double         fLength;                 //
   double         fOpenAngle;              //

   Shower();
   Shower(const Shower & );
   virtual ~Shower();

   ClassDef(Shower,15); // Generated by MakeProject.
};
} // namespace
#endif
