//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef recob__PointCharge_h
#define recob__PointCharge_h
namespace recob {
class PointCharge;
} // end of namespace.

#include "Rtypes.h"

namespace recob {
class PointCharge {

public:
// Nested classes declaration.

public:
// Data Members.
   float       fCharge;     //Reconstructed charge.

   PointCharge();
   PointCharge(const PointCharge & );
   virtual ~PointCharge();

   ClassDef(PointCharge,11); // Generated by MakeProject.
};
} // namespace
#endif
