//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef util__flags__BitMask_unsigned_int__h
#define util__flags__BitMask_unsigned_int__h
namespace util {
namespace flags {
template <typename T0> class BitMask;
template <> class BitMask<unsigned int>;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "util__flags__Bits_t_unsigned_int_.h"

namespace util {
namespace flags {
template <typename T0> class BitMask;
template <> class BitMask<unsigned int> {

public:
// Nested classes declaration.

public:
// Data Members.
   util::flags::Bits_t<unsigned int> values;      //Storage of value bits.
   util::flags::Bits_t<unsigned int> presence;    //Storage of definition bits.

   BitMask();
   BitMask(const BitMask & );
   virtual ~BitMask();

};
} // namespace
} // namespace
#endif
