//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sat Mar  9 10:19:31 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file ../../../protoDuneExampleAnalysis/v0r0/cmt/np04_raw_run005250_0014_dl9_reco_13061912_0_20181110T220718.root
//////////////////////////////////////////////////////////


#ifndef util__flags__FlagSet_32_unsigned_int__h
#define util__flags__FlagSet_32_unsigned_int__h
namespace util {
namespace flags {
template <int T0, typename T1> class FlagSet;
template <> class FlagSet<32,unsigned int>;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "util__flags__BitMask_unsigned_int_.h"

namespace util {
namespace flags {
template <int T0, typename T1> class FlagSet;
template <> class FlagSet<32,unsigned int> : public util::flags::BitMask<unsigned int> {

public:
// Nested classes declaration.

public:
// Data Members.

   FlagSet();
   FlagSet(const FlagSet & );
   virtual ~FlagSet();

};
} // namespace
} // namespace
#endif
