//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef anab__Calorimetry_h
#define anab__Calorimetry_h
namespace anab {
class Calorimetry;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "TVector3.h"
#include "geo__PlaneID.h"

namespace anab {
class Calorimetry {

public:
// Nested classes declaration.

public:
// Data Members.
   double      fKineticEnergy;    //determined kinetic energy
   vector<double> fdEdx;             //dE/dx, should be same size as fResidualRange
   vector<double> fdQdx;             //dQ/dx
   vector<double> fResidualRange;    //range from end of track
   vector<double> fDeadWireResR;     //dead wire residual range, collection plane
   double         fRange;            //total range of track
   vector<double> fTrkPitch;         //track pitch on collection plane
   vector<TVector3> fXYZ;              //coordinates of space points
   geo::PlaneID     fPlaneID;          //

   Calorimetry();
   Calorimetry(const Calorimetry & );
   virtual ~Calorimetry();

   ClassDef(Calorimetry,17); // Generated by MakeProject.
};
} // namespace
#endif
