//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef anab__CosmicTag_h
#define anab__CosmicTag_h
namespace anab {
class CosmicTag;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace anab {
class CosmicTag {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<float> endPt1;      //x,y,z assuming t_0 = t_beam
   vector<float> endPt2;      //x,y,z assuming t_0 = t_beam
   float         fCosmicScore;    //-1 means very likely neutrino,
   Int_t         fCosmicType;     //

   CosmicTag();
   CosmicTag(const CosmicTag & );
   virtual ~CosmicTag();

   ClassDef(CosmicTag,4); // Generated by MakeProject.
};
} // namespace
#endif
