//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef anab__T0_h
#define anab__T0_h
namespace anab {
class T0;
} // end of namespace.

#include "Rtypes.h"

namespace anab {
class T0 {

public:
// Nested classes declaration.

public:
// Data Members.
   double      fTime;       //Time in ns
   unsigned int fTriggerType;    //Type of trigger used. 0 - Muon Counters, 1 - Photon Detectors, 2 - Monte Carlo Truth
   int          fTriggerBits;    //An identifier for the Muon track / Flash / MCParticle used in matching.
   int          fID;             //Current size of T0 data product.
   double       fTriggerConfidence;    //Confidence with which this T0 is known.

   T0();
   T0(const T0 & );
   virtual ~T0();

   ClassDef(T0,16); // Generated by MakeProject.
};
} // namespace
#endif
