//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef art__TriggerResults_h
#define art__TriggerResults_h
namespace art {
class TriggerResults;
} // end of namespace.

#include "Rtypes.h"
#include "art__HLTGlobalStatus.h"
#include "fhicl__ParameterSetID.h"

namespace art {
class TriggerResults : public art::HLTGlobalStatus {

public:
// Nested classes declaration.

public:
// Data Members.
   fhicl::ParameterSetID psetid_;     //

   TriggerResults();
   TriggerResults(const TriggerResults & );
   virtual ~TriggerResults();

   ClassDef(TriggerResults,13); // Generated by MakeProject.
};
} // namespace
#endif
