//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef art__ProcessConfiguration_h
#define art__ProcessConfiguration_h
namespace art {
class ProcessConfiguration;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include "fhicl__ParameterSetID.h"

namespace art {
class ProcessConfiguration {

public:
// Nested classes declaration.

public:
// Data Members.
   string      processName_;    //
   fhicl::ParameterSetID parameterSetID_;    //
   string                releaseVersion_;    //

   ProcessConfiguration();
   ProcessConfiguration(const ProcessConfiguration & );
   virtual ~ProcessConfiguration();

   ClassDef(ProcessConfiguration,12); // Generated by MakeProject.
};
} // namespace
#endif
