//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef art__RNGsnapshot_h
#define art__RNGsnapshot_h
namespace art {
class RNGsnapshot;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include <vector>

namespace art {
class RNGsnapshot {

public:
// Nested classes declaration.

public:
// Data Members.
   string      engine_kind_;    //
   string      label_;          //
   vector<unsigned int> state_;          //

   RNGsnapshot();
   RNGsnapshot(const RNGsnapshot & );
   virtual ~RNGsnapshot();

   ClassDef(RNGsnapshot,11); // Generated by MakeProject.
};
} // namespace
#endif
