//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef art__ProcessHistory_h
#define art__ProcessHistory_h
namespace art {
class ProcessHistory;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "art__ProcessConfiguration.h"
#include "art__Transient_art__ProcessHistory__Transients_.h"
namespace art {
#ifndef art__ProcessHistory_h
#define art__ProcessHistory_h
enum ProcessHistory::Transients { kDefault_ProcessHistory::Transients };
#endif
} // end of namespace.

namespace art {
class ProcessHistory {

public:
// Nested classes forward declaration.
enum Transients { kDefault_Transients };

public:
// Nested classes declaration.

public:
// Data Members.
   vector<art::ProcessConfiguration> data_;       //
   art::Transient<art::ProcessHistory::Transients> transients_;    //

   ProcessHistory();
   ProcessHistory(const ProcessHistory & );
   virtual ~ProcessHistory();

   ClassDef(ProcessHistory,11); // Generated by MakeProject.
};
} // namespace
#endif
