//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef fhicl__ParameterSetID_h
#define fhicl__ParameterSetID_h
namespace fhicl {
class ParameterSetID;
} // end of namespace.

#include "Rtypes.h"

namespace fhicl {
class ParameterSetID {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        valid_;      //
   unsigned char id_[20];     //

   ParameterSetID();
   ParameterSetID(const ParameterSetID & );
   virtual ~ParameterSetID();

   ClassDef(ParameterSetID,12); // Generated by MakeProject.
};
} // namespace
#endif
