//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef geo__WireID_h
#define geo__WireID_h
namespace geo {
class WireID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__PlaneID.h"

namespace geo {
class WireID : public geo::PlaneID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int Wire;        //Index of the wire within its plane.

   WireID();
   WireID(const WireID & );
   virtual ~WireID();

   ClassDef(WireID,13); // Generated by MakeProject.
};
} // namespace
#endif
