//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef larpandoraobj__PFParticleMetadata_h
#define larpandoraobj__PFParticleMetadata_h
namespace larpandoraobj {
class PFParticleMetadata;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <map>

namespace larpandoraobj {
class PFParticleMetadata {

public:
// Nested classes declaration.

public:
// Data Members.
//   std::vector<std::pair<std::string,float> > m_propertiesMap;    //The properties map
     std::map<std::string,float > m_propertiesMap;    //The properties map

   PFParticleMetadata();
   PFParticleMetadata(const PFParticleMetadata & );
   virtual ~PFParticleMetadata();

};
} // namespace
#endif
