//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef recob__PointCharge_h
#define recob__PointCharge_h
namespace recob {
class PointCharge;
} // end of namespace.

#include "Rtypes.h"

namespace recob {
class PointCharge {

public:
// Nested classes declaration.

public:
// Data Members.
   float       fCharge;     //Reconstructed charge.

   PointCharge();
   PointCharge(const PointCharge & );
   virtual ~PointCharge();

   ClassDef(PointCharge,11); // Generated by MakeProject.
};
} // namespace
#endif
