//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef recob__OpHit_h
#define recob__OpHit_h
namespace recob {
class OpHit;
} // end of namespace.

#include "Rtypes.h"

namespace recob {
class OpHit {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fOpChannel;    //
   unsigned short fFrame;        //
   double         fPeakTime;     //
   double         fPeakTimeAbs;    //
   double         fWidth;          //
   double         fArea;           //
   double         fAmplitude;      //
   double         fPE;             //
   double         fFastToTotal;    //

   OpHit();
   OpHit(const OpHit & );
   virtual ~OpHit();

   ClassDef(OpHit,15); // Generated by MakeProject.
};
} // namespace
#endif
