//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef sim__OpDetDivRec_h
#define sim__OpDetDivRec_h
namespace sim {
class OpDetDivRec;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "sim__OpDet_Time_Chans.h"

namespace sim {
class OpDetDivRec {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fOpDetNum;    //Move this to be private.
   vector<sim::OpDet_Time_Chans> time_chans;    //Move this to private //This must be filled with emplace to keep it sorted.

   OpDetDivRec();
   OpDetDivRec(const OpDetDivRec & );
   virtual ~OpDetDivRec();

   ClassDef(OpDetDivRec,14); // Generated by MakeProject.
};
} // namespace
#endif
