//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef sim__Chan_Phot_h
#define sim__Chan_Phot_h
namespace sim {
class Chan_Phot;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class Chan_Phot {

public:
// Nested classes declaration.

public:
// Data Members.
   int         opChan;      //
   int         trackID;     //
   double      phot;        //

   Chan_Phot();
   Chan_Phot(const Chan_Phot & );
   virtual ~Chan_Phot();

};
} // namespace
#endif
