//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef sim__IDE_h
#define sim__IDE_h
namespace sim {
class IDE;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class IDE {

public:
// Nested classes declaration.

public:
// Data Members.
   int         trackID;     //Geant4 supplied track ID
   float       numElectrons;    //number of electrons at the readout for this track ID and time
   float       energy;          //energy deposited by ionization by this track ID and time [MeV]
   float       x;               //x position of ionization [cm]
   float       y;               //y position of ionization [cm]
   float       z;               //z position of ionization [cm]

   IDE();
   IDE(const IDE & );
   virtual ~IDE();

   ClassDef(IDE,12); // Generated by MakeProject.
};
} // namespace
#endif
