//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef sim__ProtoDUNEBeamInstrument_h
#define sim__ProtoDUNEBeamInstrument_h
namespace sim {
class ProtoDUNEBeamInstrument;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace sim {
class ProtoDUNEBeamInstrument {

public:
// Nested classes declaration.

public:
// Data Members.
   string      fInstrumentName;    //
   float       fX;                 //
   float       fY;                 //
   float       fZ;                 //
   float       fT;                 //
   float       fPx;                //
   float       fPy;                //
   float       fPz;                //
   int         fPDGid;             //
   int         fEventID;           //
   int         fTrackID;           //
   float       fSmearedVar1;       //
   float       fSmearedVar2;       //
   float       fResolution;        //

   ProtoDUNEBeamInstrument();
   ProtoDUNEBeamInstrument(const ProtoDUNEBeamInstrument & );
   virtual ~ProtoDUNEBeamInstrument();

   ClassDef(ProtoDUNEBeamInstrument,11); // Generated by MakeProject.
};
} // namespace
#endif
