//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef sim__OpDet_Time_Chans_h
#define sim__OpDet_Time_Chans_h
namespace sim {
class OpDet_Time_Chans;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "sim__Chan_Phot.h"

namespace sim {
class OpDet_Time_Chans {

public:
// Nested classes declaration.

public:
// Data Members.
   double      time;        //
   vector<sim::Chan_Phot> phots;       //

   OpDet_Time_Chans();
   OpDet_Time_Chans(const OpDet_Time_Chans & );
   virtual ~OpDet_Time_Chans();

};
} // namespace
#endif
