//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 14 10:40:59 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/MCC11/mcc11_protoDUNE_sp_reco_12231045_0_1ee4e6cf-25fb-482c-a231-fbd91e816aa4.root
//////////////////////////////////////////////////////////


#ifndef util__flags__Bits_t_unsigned_int__h
#define util__flags__Bits_t_unsigned_int__h
namespace util {
namespace flags {
template <typename T0> class Bits_t;
template <> class Bits_t<unsigned int>;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"

namespace util {
namespace flags {
template <typename T0> class Bits_t;
template <> class Bits_t<unsigned int> {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int data;        //The bits representing all set bits

   Bits_t();
   Bits_t(const Bits_t & );
   virtual ~Bits_t();

};
} // namespace
} // namespace
#endif
