//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef anab__MVADescription_4__h
#define anab__MVADescription_4__h
namespace anab {
template <int T0> class MVADescription;
template <> class MVADescription<4>;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace anab {
template <int T0> class MVADescription;
template <> class MVADescription<4> {

public:
// Nested classes declaration.

public:
// Data Members.
   string      fDataTag;    //Tag of the reco data products (art::InputTag format)
   string      fOutputInstance;    //Instance name of the feature vector collection
   string      fOutputNames[4];    //Feature vector entries names/meaning

   MVADescription();
   MVADescription(const MVADescription & );
   virtual ~MVADescription();

   ClassDef(MVADescription,11); // Generated by MakeProject.
};
} // namespace
#endif
