//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__Assns_recob__Cluster_recob__Vertex_unsigned_short__h
#define art__Assns_recob__Cluster_recob__Vertex_unsigned_short__h
namespace recob {
class Cluster;
} // end of namespace.
namespace recob {
class Vertex;
} // end of namespace.
namespace art {
template <typename T0, typename T1, typename T2> class Assns;
template <> class Assns<recob::Cluster,recob::Vertex,unsigned short>;
} // end of namespace.

#include "Rtypes.h"
#include "recob__Cluster.h"
#include "recob__Vertex.h"
#include "art__Assns_recob__Cluster_recob__Vertex_void_.h"
#include "Riostream.h"
#include <vector>

namespace art {
template <typename T0, typename T1, typename T2> class Assns;
template <> class Assns<recob::Cluster,recob::Vertex,unsigned short> : public art::Assns<recob::Cluster,recob::Vertex,void> {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<unsigned short> data_;       //

   Assns();
   Assns(const Assns & );
   virtual ~Assns();

   ClassDef(Assns,12); // Generated by MakeProject.
};
} // namespace
#endif
