//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__Parentage_h
#define art__Parentage_h
namespace art {
class Parentage;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "art__ProductID.h"

namespace art {
class Parentage {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<art::ProductID> parents_;    //

   Parentage();
   Parentage(const Parentage & );
   virtual ~Parentage();

   ClassDef(Parentage,12); // Generated by MakeProject.
};
} // namespace
#endif
