//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__ProcessConfiguration_h
#define art__ProcessConfiguration_h
namespace art {
class ProcessConfiguration;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include "fhicl__ParameterSetID.h"

namespace art {
class ProcessConfiguration {

public:
// Nested classes declaration.

public:
// Data Members.
   string      processName_;    //
   fhicl::ParameterSetID parameterSetID_;    //
   string                releaseVersion_;    //

   ProcessConfiguration();
   ProcessConfiguration(const ProcessConfiguration & );
   virtual ~ProcessConfiguration();

   ClassDef(ProcessConfiguration,12); // Generated by MakeProject.
};
} // namespace
#endif
