//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__Transient_art__ProcessHistory__Transients__h
#define art__Transient_art__ProcessHistory__Transients__h
namespace art {
#ifndef art__ProcessHistory_h
#define art__ProcessHistory_h
enum ProcessHistory::Transients { kDefault_ProcessHistory::Transients };
#endif
} // end of namespace.
namespace art {
template <typename T0> class Transient;
} // end of namespace.

#include "Rtypes.h"
namespace art {
#ifndef art__ProcessHistory_h
#define art__ProcessHistory_h
enum ProcessHistory::Transients { kDefault_ProcessHistory::Transients };
#endif
} // end of namespace.

#ifndef template_art__Transient_h
#define template_art__Transient_h
namespace art {
template <typename T0> class Transient {

public:
// Nested classes declaration.

public:
// Data Members.

   Transient() {
   }
   Transient(const Transient & rhs )
{
   // This is NOT a copy constructor. This is actually a move constructor (for stl container's sake).
   // Use at your own risk!
   (void)rhs; // avoid warning about unused parameter
   }
   virtual ~Transient() {
   }

};
} // namespace
#endif // generic template declaration
#endif
