//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__Wrapper_art__Assns_recob__Hit_recob__SpacePoint_void____h
#define art__Wrapper_art__Assns_recob__Hit_recob__SpacePoint_void____h
namespace recob {
class Hit;
} // end of namespace.
namespace recob {
class SpacePoint;
} // end of namespace.
namespace art {
template <typename T0, typename T1, typename T2> class Assns;
template <> class Assns<recob::Hit,recob::SpacePoint,void>;
} // end of namespace.
namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::Assns<recob::Hit,recob::SpacePoint,void> >;
} // end of namespace.

#include "Rtypes.h"
#include "art__Assns_recob__Hit_recob__SpacePoint_void_.h"
#include "art__EDProduct.h"
#include "recob__Hit.h"
#include "recob__SpacePoint.h"

namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::Assns<recob::Hit,recob::SpacePoint,void> > : public art::EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   unsigned int rangeSetID;    //
   art::Assns<recob::Hit,recob::SpacePoint,void> obj;           //

   Wrapper();
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,12); // Generated by MakeProject.
};
} // namespace
#endif
