//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__EventID_h
#define art__EventID_h
namespace art {
class EventID;
} // end of namespace.

#include "Rtypes.h"
#include "art__SubRunID.h"

namespace art {
class EventID {

public:
// Nested classes declaration.

public:
// Data Members.
   art::SubRunID subRun_;     //
   unsigned int  event_;      //

   EventID();
   EventID(const EventID & );
   virtual ~EventID();

   ClassDef(EventID,13); // Generated by MakeProject.
};
} // namespace
#endif
