//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__ResultsAuxiliary_h
#define art__ResultsAuxiliary_h
namespace art {
class ResultsAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__Hash_2_.h"
#include "Riostream.h"
#include <set>

namespace art {
class ResultsAuxiliary {

public:
// Nested classes declaration.

public:
// Data Members.
   art::Hash<2> processHistoryID_;    //
   std::vector<art::Hash<2> > allEventsProcessHistories_;    //

   ResultsAuxiliary();
   ResultsAuxiliary(const ResultsAuxiliary & );
   virtual ~ResultsAuxiliary();

   ClassDef(ResultsAuxiliary,11); // Generated by MakeProject.
};
} // namespace
#endif
