//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__TriggerResults_h
#define art__TriggerResults_h
namespace art {
class TriggerResults;
} // end of namespace.

#include "Rtypes.h"
#include "art__HLTGlobalStatus.h"
#include "fhicl__ParameterSetID.h"

namespace art {
class TriggerResults : public art::HLTGlobalStatus {

public:
// Nested classes declaration.

public:
// Data Members.
   fhicl::ParameterSetID psetid_;     //

   TriggerResults();
   TriggerResults(const TriggerResults & );
   virtual ~TriggerResults();

   ClassDef(TriggerResults,13); // Generated by MakeProject.
};
} // namespace
#endif
