//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__Wrapper_art__Assns_recob__Cluster_recob__Vertex_unsigned_short____h
#define art__Wrapper_art__Assns_recob__Cluster_recob__Vertex_unsigned_short____h
namespace recob {
class Cluster;
} // end of namespace.
namespace recob {
class Vertex;
} // end of namespace.
namespace art {
template <typename T0, typename T1, typename T2> class Assns;
template <> class Assns<recob::Cluster,recob::Vertex,unsigned short>;
} // end of namespace.
namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::Assns<recob::Cluster,recob::Vertex,unsigned short> >;
} // end of namespace.

#include "Rtypes.h"
#include "art__Assns_recob__Cluster_recob__Vertex_unsigned_short_.h"
#include "art__EDProduct.h"
#include "recob__Cluster.h"
#include "recob__Vertex.h"

namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::Assns<recob::Cluster,recob::Vertex,unsigned short> > : public art::EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   unsigned int rangeSetID;    //
   art::Assns<recob::Cluster,recob::Vertex,unsigned short> obj;           //

   Wrapper();
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,12); // Generated by MakeProject.
};
} // namespace
#endif
