//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__Wrapper_art__TriggerResults__h
#define art__Wrapper_art__TriggerResults__h
namespace art {
class TriggerResults;
} // end of namespace.
namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::TriggerResults>;
} // end of namespace.

#include "Rtypes.h"
#include "art__TriggerResults.h"
#include "art__EDProduct.h"

namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::TriggerResults> : public art::EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   unsigned int rangeSetID;    //
   art::TriggerResults obj;           //

   Wrapper();
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,12); // Generated by MakeProject.
};
} // namespace
#endif
