//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__HLTPathStatus_h
#define art__HLTPathStatus_h
namespace art {
class HLTPathStatus;
} // end of namespace.

#include "Rtypes.h"

namespace art {
class HLTPathStatus {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short status_;     //

   HLTPathStatus();
   HLTPathStatus(const HLTPathStatus & );
   virtual ~HLTPathStatus();

   ClassDef(HLTPathStatus,11); // Generated by MakeProject.
};
} // namespace
#endif
