//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef art__detail__AssnsBase_h
#define art__detail__AssnsBase_h
namespace art {
namespace detail {
class AssnsBase;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"

namespace art {
namespace detail {
class AssnsBase {

public:
// Nested classes declaration.

public:
// Data Members.

   AssnsBase();
   AssnsBase(const AssnsBase & );
   virtual ~AssnsBase();

   ClassDef(AssnsBase,11); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
