//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef artdaq__PackageBuildInfo_h
#define artdaq__PackageBuildInfo_h
namespace artdaq {
class PackageBuildInfo;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace artdaq {
class PackageBuildInfo {

public:
// Nested classes declaration.

public:
// Data Members.
   string      packageName_;    //
   string      packageVersion_;    //
   string      buildTimestamp_;    //

   PackageBuildInfo();
   PackageBuildInfo(const PackageBuildInfo & );
   virtual ~PackageBuildInfo();

   ClassDef(PackageBuildInfo,12); // Generated by MakeProject.
};
} // namespace
#endif
