//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef artdaq__QuickVec_ULong64_t__h
#define artdaq__QuickVec_ULong64_t__h
namespace artdaq {
template <typename T0> class QuickVec;
template <> class QuickVec<ULong64_t>;
} // end of namespace.

#include "Rtypes.h"

namespace artdaq {
template <typename T0> class QuickVec;
template <> class QuickVec<ULong64_t> {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int size_;       //
   ULong64_t*   data_;       //[size_]
   unsigned int capacity_;    //

   QuickVec();
   QuickVec(const QuickVec & );
   virtual ~QuickVec();

   ClassDef(QuickVec,6); // Generated by MakeProject.
};
} // namespace
#endif
