//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef artdaq__Fragment_h
#define artdaq__Fragment_h
namespace artdaq {
class Fragment;
} // end of namespace.

#include "Rtypes.h"
#include "artdaq__QuickVec_ULong64_t_.h"

namespace artdaq {
class Fragment {

public:
// Nested classes declaration.

public:
// Data Members.
   artdaq::QuickVec<ULong64_t> vals_;       //

   Fragment();
   Fragment(const Fragment & );
   virtual ~Fragment();

   ClassDef(Fragment,16); // Generated by MakeProject.
};
} // namespace
#endif
