//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef beam__CKov_h
#define beam__CKov_h
namespace beam {
class CKov;
} // end of namespace.

#include "Rtypes.h"

namespace beam {
class CKov {

public:
// Nested classes declaration.

public:
// Data Members.
   short       trigger;     //
   double      pressure;    //
   double      timeStamp;    //

   CKov();
   CKov(const CKov & );
   virtual ~CKov();

};
} // namespace
#endif
