//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:50 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef beam__FBM_h
#define beam__FBM_h
namespace beam {
class FBM;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace beam {
class FBM {

public:
// Nested classes declaration.

public:
// Data Members.
   short       fibers[192];    //
   double      fiberData[6];    //
   double      timeData[4];     //
   double      timeStamp;       //
   int         ID;              //
   vector<short> active;          //
   bool          decoded;         //

   FBM();
   FBM(const FBM & );
   virtual ~FBM();

};
} // namespace
#endif
