//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef CRT__Trigger_h
#define CRT__Trigger_h
namespace CRT {
class Trigger;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
namespace CRT {
#ifndef CRT__Hit_h
#define CRT__Hit_h
enum Hit { kDefault_Hit };
#endif
} // end of namespace.

namespace CRT {
class Trigger {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short fChannel;    //Mapping to CRT module that was Triggered.  Index into the Geometry service's array of AuxDetGeos
   ULong64_t      fTimestamp;    //Timestamp when this Trigger occurred.  First 32 bits are Linux time since epoch; last 32 bits are time in
   vector<CRT::Hit> fHits;         //All activity in CRT strips within this module when it was read out

   Trigger();
   Trigger(const Trigger & );
   virtual ~Trigger();

   ClassDef(Trigger,11); // Generated by MakeProject.
};
} // namespace
#endif
