//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:49 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef fhicl__ParameterSetID_h
#define fhicl__ParameterSetID_h
namespace fhicl {
class ParameterSetID;
} // end of namespace.

#include "Rtypes.h"

namespace fhicl {
class ParameterSetID {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        valid_;      //
   unsigned char id_[20];     //

   ParameterSetID();
   ParameterSetID(const ParameterSetID & );
   virtual ~ParameterSetID();

   ClassDef(ParameterSetID,12); // Generated by MakeProject.
};
} // namespace
#endif
