//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:50 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef raw__ctb__Feedback_h
#define raw__ctb__Feedback_h
namespace raw {
namespace ctb {
class Feedback;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"

#endif
