//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:50 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef raw__ctb__WordIndex_h
#define raw__ctb__WordIndex_h
namespace raw {
namespace ctb {
class WordIndex;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"

namespace raw {
namespace ctb {
class WordIndex {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int word_type;    //
   unsigned int index;        //

   WordIndex();
   WordIndex(const WordIndex & );
   virtual ~WordIndex();

   ClassDef(WordIndex,11); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
