//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:50 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef raw__ctb__Trigger_h
#define raw__ctb__Trigger_h
namespace raw {
namespace ctb {
class Trigger;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"

namespace raw {
namespace ctb {
class Trigger {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int word_type;    //
   ULong64_t    trigger_word;    //
   ULong64_t    timestamp;       //

   Trigger();
   Trigger(const Trigger & );
   virtual ~Trigger();

   ClassDef(Trigger,11); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
