//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:50 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef recob__TrackTrajectory_h
#define recob__TrackTrajectory_h
namespace recob {
class TrackTrajectory;
} // end of namespace.

#include "Rtypes.h"
#include "recob__Trajectory.h"
#include "Riostream.h"
#include <vector>
#include "recob__TrajectoryPointFlags.h"

namespace recob {
class TrackTrajectory : public recob::Trajectory {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<recob::TrajectoryPointFlags> fFlags;      //Flags of each of the points in trajectory

   TrackTrajectory();
   TrackTrajectory(const TrackTrajectory & );
   virtual ~TrackTrajectory();

   ClassDef(TrackTrajectory,12); // Generated by MakeProject.
};
} // namespace
#endif
