//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:50 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef recob__SpacePoint_h
#define recob__SpacePoint_h
namespace recob {
class SpacePoint;
} // end of namespace.

#include "Rtypes.h"

namespace recob {
class SpacePoint {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fID;         //SpacePoint ID
   Double32_t  fXYZ[3];     //position of SpacePoint in xyz
   Double32_t  fErrXYZ[6];    //Error matrix (triangular).
   Double32_t  fChisq;        //Chisquare.

   SpacePoint();
   SpacePoint(const SpacePoint & );
   virtual ~SpacePoint();

   ClassDef(SpacePoint,14); // Generated by MakeProject.
};
} // namespace
#endif
