//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jun  3 14:12:50 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /hep/DUNE/DataDir/ana_-043d807f-0b76-401e-9889-c1184b96a71c.root
//////////////////////////////////////////////////////////


#ifndef recob__PCAxis_h
#define recob__PCAxis_h
namespace recob {
class PCAxis;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;

namespace recob {
class PCAxis {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        fSvdOK;      //SVD Decomposition was successful
   int         fNumHitsUsed;    //Number of hits in the decomposition
   double      fEigenValues[3];    //Eigen values from SVD decomposition
   vector<vector<double> > fEigenVectors;      //The three principle axes
   double                  fAvePosition[3];    //Average position of hits fed to PCA
   double                  fAveHitDoca;        //Average doca of hits used in PCA
   unsigned long           fID;                //axis ID

   PCAxis();
   PCAxis(const PCAxis & );
   virtual ~PCAxis();

   ClassDef(PCAxis,13); // Generated by MakeProject.
};
} // namespace
#endif
