//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef anab__CosmicTag_h
#define anab__CosmicTag_h
namespace anab {
class CosmicTag;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace anab {
class CosmicTag {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<float> endPt1;      //x,y,z assuming t_0 = t_beam
   vector<float> endPt2;      //x,y,z assuming t_0 = t_beam
   float         fCosmicScore;    //-1 means very likely neutrino,
   Int_t         fCosmicType;     //

   CosmicTag();
   CosmicTag(const CosmicTag & );
   virtual ~CosmicTag();

   ClassDef(CosmicTag,4); // Generated by MakeProject.
};
} // namespace
#endif
