//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef anab__T0_h
#define anab__T0_h
namespace anab {
class T0;
} // end of namespace.

#include "Rtypes.h"

namespace anab {
class T0 {

public:
// Nested classes declaration.

public:
// Data Members.
   double      fTime;       //Time in ns
   unsigned int fTriggerType;    //Type of trigger used. 0 - Muon Counters, 1 - Photon Detectors, 2 - Monte Carlo Truth
   int          fTriggerBits;    //An identifier for the Muon track / Flash / MCParticle used in matching.
   int          fID;             //Current size of T0 data product.
   double       fTriggerConfidence;    //Confidence with which this T0 is known.

   T0();
   T0(const T0 & );
   virtual ~T0();

   ClassDef(T0,16); // Generated by MakeProject.
};
} // namespace
#endif
