//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef art__Transient_art__BranchDescription__Transients__h
#define art__Transient_art__BranchDescription__Transients__h
namespace art {
#ifndef art__BranchDescription_h
#define art__BranchDescription_h
enum BranchDescription::Transients { kDefault_BranchDescription::Transients };
#endif
} // end of namespace.
namespace art {
template <typename T0> class Transient;
} // end of namespace.

#include "Rtypes.h"
namespace art {
#ifndef art__BranchDescription_h
#define art__BranchDescription_h
enum BranchDescription::Transients { kDefault_BranchDescription::Transients };
#endif
} // end of namespace.

#ifndef template_art__Transient_h
#define template_art__Transient_h
namespace art {
template <typename T0> class Transient {

public:
// Nested classes declaration.

public:
// Data Members.

   Transient() {
   }
   Transient(const Transient & rhs )
{
   // This is NOT a copy constructor. This is actually a move constructor (for stl container's sake).
   // Use at your own risk!
   (void)rhs; // avoid warning about unused parameter
   }
   virtual ~Transient() {
   }

};
} // namespace
#endif // generic template declaration
#endif
