//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef art__ProcessConfiguration_h
#define art__ProcessConfiguration_h
namespace art {
class ProcessConfiguration;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include "fhicl__ParameterSetID.h"

namespace art {
class ProcessConfiguration {

public:
// Nested classes declaration.

public:
// Data Members.
   string      processName_;    //
   fhicl::ParameterSetID parameterSetID_;    //
   string                releaseVersion_;    //

   ProcessConfiguration();
   ProcessConfiguration(const ProcessConfiguration & );
   virtual ~ProcessConfiguration();

   ClassDef(ProcessConfiguration,12); // Generated by MakeProject.
};
} // namespace
#endif
