//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef art__ProductID_h
#define art__ProductID_h
namespace art {
class ProductID;
} // end of namespace.

#include "Rtypes.h"

namespace art {
class ProductID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int value_;      //

   ProductID();
   ProductID(const ProductID & );
   virtual ~ProductID();

   ClassDef(ProductID,11); // Generated by MakeProject.
};
} // namespace
#endif
