//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef art__Wrapper_art__TriggerResults__h
#define art__Wrapper_art__TriggerResults__h
namespace art {
class TriggerResults;
} // end of namespace.
namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::TriggerResults>;
} // end of namespace.

#include "Rtypes.h"
#include "art__TriggerResults.h"
#include "art__EDProduct.h"

namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::TriggerResults> : public art::EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   unsigned int rangeSetID;    //
   art::TriggerResults obj;           //

   Wrapper();
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,12); // Generated by MakeProject.
};
} // namespace
#endif
