//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef art__SubRunAuxiliary_h
#define art__SubRunAuxiliary_h
namespace art {
class SubRunAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__Hash_2_.h"
#include "art__SubRunID.h"
#include "art__Timestamp.h"

namespace art {
class SubRunAuxiliary {

public:
// Nested classes declaration.

public:
// Data Members.
   art::Hash<2> processHistoryID_;    //
   unsigned int rangeSetID_;          //
   art::SubRunID id_;                  //
   art::Timestamp beginTime_;           //
   art::Timestamp endTime_;             //

   SubRunAuxiliary();
   SubRunAuxiliary(const SubRunAuxiliary & );
   virtual ~SubRunAuxiliary();

   ClassDef(SubRunAuxiliary,12); // Generated by MakeProject.
};
} // namespace
#endif
