//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef art__Wrapper_art__Assns_CRT__Trigger_anab__CosmicTag_void____h
#define art__Wrapper_art__Assns_CRT__Trigger_anab__CosmicTag_void____h
namespace CRT {
class Trigger;
} // end of namespace.
namespace anab {
class CosmicTag;
} // end of namespace.
namespace art {
template <typename T0, typename T1, typename T2> class Assns;
template <> class Assns<CRT::Trigger,anab::CosmicTag,void>;
} // end of namespace.
namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::Assns<CRT::Trigger,anab::CosmicTag,void> >;
} // end of namespace.

#include "Rtypes.h"
#include "art__Assns_CRT__Trigger_anab__CosmicTag_void_.h"
#include "art__EDProduct.h"
#include "CRT__Trigger.h"
#include "anab__CosmicTag.h"

namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::Assns<CRT::Trigger,anab::CosmicTag,void> > : public art::EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   unsigned int rangeSetID;    //
   art::Assns<CRT::Trigger,anab::CosmicTag,void> obj;           //

   Wrapper();
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,12); // Generated by MakeProject.
};
} // namespace
#endif
