//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef artdaq__Fragment_h
#define artdaq__Fragment_h
namespace artdaq {
class Fragment;
} // end of namespace.

#include "Rtypes.h"
#include "artdaq__QuickVec_ULong64_t_.h"

namespace artdaq {
class Fragment {

public:
// Nested classes declaration.

public:
// Data Members.
   artdaq::QuickVec<ULong64_t> vals_;       //

   Fragment();
   Fragment(const Fragment & );
   virtual ~Fragment();

   ClassDef(Fragment,16); // Generated by MakeProject.
};
} // namespace
#endif
