//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef artdaq__QuickVec_ULong64_t__h
#define artdaq__QuickVec_ULong64_t__h
namespace artdaq {
template <typename T0> class QuickVec;
template <> class QuickVec<ULong64_t>;
} // end of namespace.

#include "Rtypes.h"

namespace artdaq {
template <typename T0> class QuickVec;
template <> class QuickVec<ULong64_t> {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int size_;       //
   ULong64_t*   data_;       //[size_]
   unsigned int capacity_;    //

   QuickVec();
   QuickVec(const QuickVec & );
   virtual ~QuickVec();

   ClassDef(QuickVec,6); // Generated by MakeProject.
};
} // namespace
#endif
