//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef artdaq__PackageBuildInfo_h
#define artdaq__PackageBuildInfo_h
namespace artdaq {
class PackageBuildInfo;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace artdaq {
class PackageBuildInfo {

public:
// Nested classes declaration.

public:
// Data Members.
   string      packageName_;    //
   string      packageVersion_;    //
   string      buildTimestamp_;    //

   PackageBuildInfo();
   PackageBuildInfo(const PackageBuildInfo & );
   virtual ~PackageBuildInfo();

   ClassDef(PackageBuildInfo,12); // Generated by MakeProject.
};
} // namespace
#endif
