//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef beam__FBM_h
#define beam__FBM_h
namespace beam {
class FBM;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace beam {
class FBM {

public:
// Nested classes declaration.

public:
// Data Members.
   short       fibers[192];    //
   double      fiberData[6];    //
   double      timeData[4];     //
   double      timeStamp;       //
   int         ID;              //
   vector<short> active;          //
   bool          decoded;         //

   FBM();
   FBM(const FBM & );
   virtual ~FBM();

};
} // namespace
#endif
