//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef CRT__Hit_h
#define CRT__Hit_h
namespace CRT {
class Hit;
} // end of namespace.

#include "Rtypes.h"

namespace CRT {
class Hit {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long fChannel;    //The index of the AuxDetSensitiveGeo that represents this strip in a CRT module
   short         fADC;        //Baseline-subtracted Analog to Digital Converter value at time when this hit was read out.

   Hit();
   Hit(const Hit & );
   virtual ~Hit();

   ClassDef(Hit,11); // Generated by MakeProject.
};
} // namespace
#endif
