//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef geo__CryostatID_h
#define geo__CryostatID_h
namespace geo {
class CryostatID;
} // end of namespace.

#include "Rtypes.h"

namespace geo {
class CryostatID {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        isValid;     //Whether this ID points to a valid element.
   unsigned int Cryostat;    //Index of cryostat.

   CryostatID();
   CryostatID(const CryostatID & );
   virtual ~CryostatID();

   ClassDef(CryostatID,19); // Generated by MakeProject.
};
} // namespace
#endif
