//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef geo__PlaneID_h
#define geo__PlaneID_h
namespace geo {
class PlaneID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__TPCID.h"

namespace geo {
class PlaneID : public geo::TPCID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int Plane;       //Index of the plane within its TPC.

   PlaneID();
   PlaneID(const PlaneID & );
   virtual ~PlaneID();

   ClassDef(PlaneID,4); // Generated by MakeProject.
};
} // namespace
#endif
