//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef geo__TPCID_h
#define geo__TPCID_h
namespace geo {
class TPCID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__CryostatID.h"

namespace geo {
class TPCID : public geo::CryostatID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int TPC;         //Index of the TPC within its cryostat.

   TPCID();
   TPCID(const TPCID & );
   virtual ~TPCID();

   ClassDef(TPCID,19); // Generated by MakeProject.
};
} // namespace
#endif
