//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef larpandoraobj__PFParticleMetadata_h
#define larpandoraobj__PFParticleMetadata_h
namespace larpandoraobj {
class PFParticleMetadata;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <map>

namespace larpandoraobj {
class PFParticleMetadata {

public:
// Nested classes declaration.

public:
// Data Members.
//   std::vector<std::pair<std::string,float> > m_propertiesMap;    //The properties map
   std::map<std::string,float > m_propertiesMap;    //The properties map

   PFParticleMetadata();
   PFParticleMetadata(const PFParticleMetadata & );
   virtual ~PFParticleMetadata();

   ClassDef(PFParticleMetadata,13); // Generated by MakeProject.
};
} // namespace
#endif
