//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef raw__RDStatus_h
#define raw__RDStatus_h
namespace raw {
class RDStatus;
} // end of namespace.

#include "Rtypes.h"

namespace raw {
class RDStatus {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        fCorruptDataDropped;    //True if some data suspected to be corrupt were not decoded
   bool        fCorruptDataKept;       //True if some data suspected to be corrupt were decoded
   unsigned int fStatWord;              //

   RDStatus();
   RDStatus(const RDStatus & );
   virtual ~RDStatus();

   ClassDef(RDStatus,11); // Generated by MakeProject.
};
} // namespace
#endif
