//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef raw__RawDigit_h
#define raw__RawDigit_h
namespace raw {
class RawDigit;
} // end of namespace.

#include "Rtypes.h"

#endif
