//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef raw__ctb__WordIndex_h
#define raw__ctb__WordIndex_h
namespace raw {
namespace ctb {
class WordIndex;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"

namespace raw {
namespace ctb {
class WordIndex {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int word_type;    //
   unsigned int index;        //

   WordIndex();
   WordIndex(const WordIndex & );
   virtual ~WordIndex();

   ClassDef(WordIndex,11); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
