//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef recob__Wire_h
#define recob__Wire_h
namespace recob {
class Wire;
} // end of namespace.

#include "Rtypes.h"
#include "lar__sparse_vector_float_.h"

namespace recob {
class Wire {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fChannel;    //ID of the associated channel.
   Int_t        fView;       //View corresponding to the plane of this wire.
   lar::sparse_vector<float> fSignalROI;    //Signal on the channel as function of time tick.

   Wire();
   Wire(const Wire & );
   virtual ~Wire();

   ClassDef(Wire,20); // Generated by MakeProject.
};
} // namespace
#endif
