//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef recob__Slice_h
#define recob__Slice_h
namespace recob {
class Slice;
} // end of namespace.

#include "Rtypes.h"
#include "Math/GenVector/PositionVector3D.h"
#include "Math/GenVector/Cartesian3D.h"
#include "Math/GenVector/CoordinateSystemTags.h"
#include "Math/GenVector/DisplacementVector3D.h"

namespace recob {
class Slice {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fID;         //id for this slice
   ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::GlobalCoordinateSystemTag> fCenter;     //Center of the slice for flash matching
   ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::GlobalCoordinateSystemTag> fDirection;    //direction from a linear fit
   ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::GlobalCoordinateSystemTag>     fEnd0Pos;      //Position of a SpacePoint at one end of the slice
   ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::GlobalCoordinateSystemTag>     fEnd1Pos;      //Position of the other end
   float                                                                                                       fAspectRatio;    //absolute value of the linear correlation coefficient (0 = round blob, 1 = line)
   float                                                                                                       fCharge;         //

   Slice();
   Slice(const Slice & );
   virtual ~Slice();

   ClassDef(Slice,16); // Generated by MakeProject.
};
} // namespace
#endif
