//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:08:35 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../np04_raw_run005834_0126_dl7_reco_22481932_0_20190828T190321.root
//////////////////////////////////////////////////////////


#ifndef util__flags__FlagSet_32_unsigned_int__h
#define util__flags__FlagSet_32_unsigned_int__h
namespace util {
namespace flags {
template <int T0, typename T1> class FlagSet;
template <> class FlagSet<32,unsigned int>;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "util__flags__BitMask_unsigned_int_.h"

namespace util {
namespace flags {
template <int T0, typename T1> class FlagSet;
template <> class FlagSet<32,unsigned int> : public util::flags::BitMask<unsigned int> {

public:
// Nested classes declaration.

public:
// Data Members.

   FlagSet();
   FlagSet(const FlagSet & );
   virtual ~FlagSet();

};
} // namespace
} // namespace
#endif
