//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef anab__T0_h
#define anab__T0_h
namespace anab {
class T0;
} // end of namespace.

#include "Rtypes.h"

namespace anab {
class T0 {

public:
// Nested classes declaration.

public:
// Data Members.
   double      fTime;       //Time in ns
   unsigned int fTriggerType;    //Type of trigger used. 0 - Muon Counters, 1 - Photon Detectors, 2 - Monte Carlo Truth
   int          fTriggerBits;    //An identifier for the Muon track / Flash / MCParticle used in matching.
   int          fID;             //Current size of T0 data product.
   double       fTriggerConfidence;    //Confidence with which this T0 is known.

   T0();
   T0(T0 && ) = default;
   T0(const T0 & );
   virtual ~T0();

   ClassDef(T0,16); // Generated by MakeProject.
};
} // namespace
#endif
