//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef art__BranchChildren_h
#define art__BranchChildren_h
namespace art {
class BranchChildren;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <map>
#include "art__ProductID.h"
#include <set>
namespace std {} using namespace std;
#ifdef __MAKECINT__
#pragma link C++ class pair<art::ProductID,vector<art::ProductID> >+;
#endif

namespace art {
class BranchChildren {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<std::pair<art::ProductID,std::vector<art::ProductID> > > childLookup_;    //

   BranchChildren();
   BranchChildren(BranchChildren && ) = default;
   BranchChildren(const BranchChildren & );
   virtual ~BranchChildren();

   ClassDef(BranchChildren,12); // Generated by MakeProject.
};
} // namespace
#endif
