//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef art__EventAuxiliary_h
#define art__EventAuxiliary_h
namespace art {
class EventAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__EventID.h"
#include "art__Timestamp.h"

namespace art {
class EventAuxiliary {

public:
// Nested classes forward declaration.
enum ExperimentType { kDefault_ExperimentType };

public:
// Nested classes declaration.

public:
// Data Members.
   art::EventID id_;         //
   art::Timestamp time_;       //
   bool           isRealData_;    //
   Int_t          experimentType_;    //

   EventAuxiliary();
   EventAuxiliary(EventAuxiliary && ) = default;
   EventAuxiliary(const EventAuxiliary & );
   virtual ~EventAuxiliary();

   ClassDef(EventAuxiliary,12); // Generated by MakeProject.
};
} // namespace
#endif
