//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__ProcessConfiguration_h
#define art__ProcessConfiguration_h
namespace art {
class ProcessConfiguration;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include "fhicl__ParameterSetID.h"

namespace art {
class ProcessConfiguration {

public:
// Nested classes declaration.

public:
// Data Members.
   string      processName_;    //
   fhicl::ParameterSetID parameterSetID_;    //
   string                releaseVersion_;    //

   ProcessConfiguration();
   ProcessConfiguration(const ProcessConfiguration & );
   virtual ~ProcessConfiguration();

   ClassDef(ProcessConfiguration,12); // Generated by MakeProject.
};
} // namespace
#endif
