//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef art__SubRunAuxiliary_h
#define art__SubRunAuxiliary_h
namespace art {
class SubRunAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__Hash_2_.h"
#include "art__SubRunID.h"
#include "art__Timestamp.h"

namespace art {
class SubRunAuxiliary {

public:
// Nested classes declaration.

public:
// Data Members.
   art::Hash<2> processHistoryID_;    //
   unsigned int rangeSetID_;          //
   art::SubRunID id_;                  //
   art::Timestamp beginTime_;           //
   art::Timestamp endTime_;             //

   SubRunAuxiliary();
   SubRunAuxiliary(SubRunAuxiliary && ) = default;
   SubRunAuxiliary(const SubRunAuxiliary & );
   virtual ~SubRunAuxiliary();

   ClassDef(SubRunAuxiliary,12); // Generated by MakeProject.
};
} // namespace
#endif
