//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__BranchChildren_h
#define art__BranchChildren_h
namespace art {
class BranchChildren;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <map>
#include "art__ProductID.h"
#include <set>
namespace std {} using namespace std;
#ifdef __MAKECINT__
#pragma link C++ class pair<art::ProductID,vector<art::ProductID> >+;
#endif

namespace art {
class BranchChildren {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<std::pair<art::ProductID,std::vector<art::ProductID> > > childLookup_;    //

   BranchChildren();
   BranchChildren(const BranchChildren & );
   virtual ~BranchChildren();

   ClassDef(BranchChildren,12); // Generated by MakeProject.
};
} // namespace
#endif
