//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef art__RefCore_h
#define art__RefCore_h
namespace art {
class RefCore;
} // end of namespace.

#include "Rtypes.h"
#include "art__ProductID.h"
#include "art__RefCore.h"

namespace art {
class RefCore {

public:
// Nested classes forward declaration.
class RefCoreTransients;

public:
// Nested classes declaration.
class RefCoreTransients {

public:
// Nested classes declaration.

public:
// Data Members.

   RefCoreTransients();
   RefCoreTransients(RefCoreTransients && ) = default;
   RefCoreTransients(const RefCoreTransients & );
   virtual ~RefCoreTransients();

   ClassDef(RefCoreTransients,11); // Generated by MakeProject.
};

public:
// Data Members.
   art::ProductID id_;         //
   art::RefCore::RefCoreTransients transients_;    //

   RefCore();
   RefCore(RefCore && ) = default;
   RefCore(const RefCore & );
   virtual ~RefCore();

   ClassDef(RefCore,11); // Generated by MakeProject.
};
} // namespace
#endif
