//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__HLTPathStatus_h
#define art__HLTPathStatus_h
namespace art {
class HLTPathStatus;
} // end of namespace.

#include "Rtypes.h"

namespace art {
class HLTPathStatus {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short status_;     //

   HLTPathStatus();
   HLTPathStatus(const HLTPathStatus & );
   virtual ~HLTPathStatus();

   ClassDef(HLTPathStatus,11); // Generated by MakeProject.
};
} // namespace
#endif
