//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__Wrapper_art__TriggerResults__h
#define art__Wrapper_art__TriggerResults__h
namespace art {
class TriggerResults;
} // end of namespace.
namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::TriggerResults>;
} // end of namespace.

#include "Rtypes.h"
#include "art__TriggerResults.h"
#include "art__EDProduct.h"

namespace art {
template <typename T0> class Wrapper;
template <> class Wrapper<art::TriggerResults> : public art::EDProduct {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   unsigned int rangeSetID;    //
   art::TriggerResults obj;           //

   Wrapper();
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,12); // Generated by MakeProject.
};
} // namespace
#endif
