//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef art__RNGsnapshot_h
#define art__RNGsnapshot_h
namespace art {
class RNGsnapshot;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include <vector>

namespace art {
class RNGsnapshot {

public:
// Nested classes declaration.

public:
// Data Members.
   string      engine_kind_;    //
   string      label_;          //
   vector<unsigned int> state_;          //

   RNGsnapshot();
   RNGsnapshot(RNGsnapshot && ) = default;
   RNGsnapshot(const RNGsnapshot & );
   virtual ~RNGsnapshot();

   ClassDef(RNGsnapshot,11); // Generated by MakeProject.
};
} // namespace
#endif
