//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__FileFormatVersion_h
#define art__FileFormatVersion_h
namespace art {
class FileFormatVersion;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace art {
class FileFormatVersion {

public:
// Nested classes declaration.

public:
// Data Members.
   int         value_;      //
   string      era_;        //

   FileFormatVersion();
   FileFormatVersion(const FileFormatVersion & );
   virtual ~FileFormatVersion();

   ClassDef(FileFormatVersion,11); // Generated by MakeProject.
};
} // namespace
#endif
