//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__ProductProvenance_h
#define art__ProductProvenance_h
namespace art {
class ProductProvenance;
} // end of namespace.

#include "Rtypes.h"
#include "art__ProductID.h"
#include "art__Hash_5_.h"
#include "art__Transient_art__ProductProvenance__Transients_.h"
namespace art {
#ifndef art__ProductProvenance_h
#define art__ProductProvenance_h
enum ProductProvenance::Transients { kDefault_ProductProvenance::Transients };
#endif
} // end of namespace.

namespace art {
class ProductProvenance {

public:
// Nested classes forward declaration.
enum Transients { kDefault_Transients };

public:
// Nested classes declaration.

public:
// Data Members.
   art::ProductID productID_;    //
   unsigned char  productStatus_;    //
   art::Hash<5>   parentageID_;      //
   art::Transient<art::ProductProvenance::Transients> transients_;       //

   ProductProvenance();
   ProductProvenance(const ProductProvenance & );
   virtual ~ProductProvenance();

   ClassDef(ProductProvenance,12); // Generated by MakeProject.
};
} // namespace
#endif
