//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef art__Hash_3__h
#define art__Hash_3__h
namespace art {
template <int T0> class Hash;
template <> class Hash<3>;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace art {
template <int T0> class Hash;
template <> class Hash<3> {

public:
// Nested classes declaration.

public:
// Data Members.
   string      hash_;       //

   Hash();
   Hash(Hash && ) = default;
   Hash(const Hash & );
   virtual ~Hash();

   ClassDef(Hash,11); // Generated by MakeProject.
};
} // namespace
#endif
