//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__SubRunAuxiliary_h
#define art__SubRunAuxiliary_h
namespace art {
class SubRunAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__Hash_2_.h"
#include "art__SubRunID.h"
#include "art__Timestamp.h"

namespace art {
class SubRunAuxiliary {

public:
// Nested classes declaration.

public:
// Data Members.
   art::Hash<2> processHistoryID_;    //
   unsigned int rangeSetID_;          //
   art::SubRunID id_;                  //
   art::Timestamp beginTime_;           //
   art::Timestamp endTime_;             //

   SubRunAuxiliary();
   SubRunAuxiliary(const SubRunAuxiliary & );
   virtual ~SubRunAuxiliary();

   ClassDef(SubRunAuxiliary,12); // Generated by MakeProject.
};
} // namespace
#endif
