//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__ResultsAuxiliary_h
#define art__ResultsAuxiliary_h
namespace art {
class ResultsAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__Hash_2_.h"
#include "Riostream.h"
#include <set>

namespace art {
class ResultsAuxiliary {

public:
// Nested classes declaration.

public:
// Data Members.
   art::Hash<2> processHistoryID_;    //
   std::vector<art::Hash<2> > allEventsProcessHistories_;    //

   ResultsAuxiliary();
   ResultsAuxiliary(const ResultsAuxiliary & );
   virtual ~ResultsAuxiliary();

   ClassDef(ResultsAuxiliary,11); // Generated by MakeProject.
};
} // namespace
#endif
