//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__FileIndex__Element_h
#define art__FileIndex__Element_h
namespace art {
namespace FileIndex {
class Element;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "art__EventID.h"

namespace art {
namespace FileIndex {
class Element {

public:
// Nested classes declaration.

public:
// Data Members.
   art::EventID eventID_;    //
   Long64_t     entry_;      //

   Element();
   Element(const Element & );
   virtual ~Element();

   ClassDef(Element,12); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
