//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__ProductRegistry_h
#define art__ProductRegistry_h
namespace art {
class ProductRegistry;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <map>
#include "art__BranchKey.h"
#include "art__BranchDescription.h"
#ifdef __MAKECINT__
#pragma link C++ class pair<art::BranchKey,art::BranchDescription >+;
#endif

namespace art {
class ProductRegistry {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<std::pair<art::BranchKey,art::BranchDescription> > productList_;    //

   ProductRegistry();
   ProductRegistry(const ProductRegistry & );
   virtual ~ProductRegistry();

   ClassDef(ProductRegistry,13); // Generated by MakeProject.
};
} // namespace
#endif
