//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef art__EventAuxiliary_h
#define art__EventAuxiliary_h
namespace art {
class EventAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__EventID.h"
#include "art__Timestamp.h"

namespace art {
class EventAuxiliary {

public:
// Nested classes forward declaration.
enum ExperimentType { kDefault_ExperimentType };

public:
// Nested classes declaration.

public:
// Data Members.
   art::EventID id_;         //
   art::Timestamp time_;       //
   bool           isRealData_;    //
   Int_t          experimentType_;    //

   EventAuxiliary();
   EventAuxiliary(const EventAuxiliary & );
   virtual ~EventAuxiliary();

   ClassDef(EventAuxiliary,12); // Generated by MakeProject.
};
} // namespace
#endif
