//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef CRT__Hit_h
#define CRT__Hit_h
namespace CRT {
class Hit;
} // end of namespace.

#include "Rtypes.h"

namespace CRT {
class Hit {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long fChannel;    //The index of the AuxDetSensitiveGeo that represents this strip in a CRT module
   short         fADC;        //Baseline-subtracted Analog to Digital Converter value at time when this hit was read out.

   Hit();
   Hit(Hit && ) = default;
   Hit(const Hit & );
   virtual ~Hit();

   ClassDef(Hit,11); // Generated by MakeProject.
};
} // namespace
#endif
