//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef CRT__Hit_h
#define CRT__Hit_h
namespace CRT {
class Hit;
} // end of namespace.

#include "Rtypes.h"

namespace CRT {
class Hit {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long fChannel;    //The index of the AuxDetSensitiveGeo that represents this strip in a CRT module
   short         fADC;        //Baseline-subtracted Analog to Digital Converter value at time when this hit was read out.

   Hit();
   Hit(const Hit & );
   virtual ~Hit();

   ClassDef(Hit,11); // Generated by MakeProject.
};
} // namespace
#endif
