//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef geo__PlaneID_h
#define geo__PlaneID_h
namespace geo {
class PlaneID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__TPCID.h"

namespace geo {
class PlaneID : public geo::TPCID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int Plane;       //Index of the plane within its TPC.

   PlaneID();
   PlaneID(PlaneID && ) = default;
   PlaneID(const PlaneID & );
   virtual ~PlaneID();

   ClassDef(PlaneID,4); // Generated by MakeProject.
};
} // namespace
#endif
