//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef geo__PlaneID_h
#define geo__PlaneID_h
namespace geo {
class PlaneID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__TPCID.h"

namespace geo {
class PlaneID : public geo::TPCID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int Plane;       //Index of the plane within its TPC.

   PlaneID();
   PlaneID(const PlaneID & );
   virtual ~PlaneID();

   ClassDef(PlaneID,4); // Generated by MakeProject.
};
} // namespace
#endif
