//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef geo__WireID_h
#define geo__WireID_h
namespace geo {
class WireID;
} // end of namespace.

#include "Rtypes.h"
#include "geo__PlaneID.h"

namespace geo {
class WireID : public geo::PlaneID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int Wire;        //Index of the wire within its plane.

   WireID();
   WireID(WireID && ) = default;
   WireID(const WireID & );
   virtual ~WireID();

   ClassDef(WireID,13); // Generated by MakeProject.
};
} // namespace
#endif
