//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef geo__CryostatID_h
#define geo__CryostatID_h
namespace geo {
class CryostatID;
} // end of namespace.

#include "Rtypes.h"

namespace geo {
class CryostatID {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        isValid;     //Whether this ID points to a valid element.
   unsigned int Cryostat;    //Index of cryostat.

   CryostatID();
   CryostatID(const CryostatID & );
   virtual ~CryostatID();

   ClassDef(CryostatID,19); // Generated by MakeProject.
};
} // namespace
#endif
