//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef lar__range_t_unsigned_long__h
#define lar__range_t_unsigned_long__h
namespace lar {
template <typename T0> class range_t;
template <> class range_t<unsigned long>;
} // end of namespace.

#include "Rtypes.h"

namespace lar {
template <typename T0> class range_t;
template <> class range_t<unsigned long> {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long offset;      //offset (absolute index) of the first element
   unsigned long last;        //offset (absolute index) after the last element

   range_t();
   range_t(range_t && ) = default;
   range_t(const range_t & );
   virtual ~range_t();

};
} // namespace
#endif
