//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef raw__RawDigit_h
#define raw__RawDigit_h
namespace raw {
class RawDigit;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace raw {
class RawDigit {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<short> fADC;        //ADC readout per tick, before pedestal subtraction
   unsigned int  fChannel;    //channel number in the readout
   unsigned short fSamples;    //number of ticks of the clock
   float          fPedestal;    //pedestal for this channel
   float          fSigma;       //sigma of the pedestal counts for this channel
   Int_t          fCompression;    //compression scheme used for the ADC vector

   RawDigit();
   RawDigit(const RawDigit & );
   virtual ~RawDigit();

   ClassDef(RawDigit,15); // Generated by MakeProject.
};
} // namespace
#endif
