//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef recob__PCAxis_h
#define recob__PCAxis_h
namespace recob {
class PCAxis;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;

namespace recob {
class PCAxis {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        fSvdOK;      //SVD Decomposition was successful
   int         fNumHitsUsed;    //Number of hits in the decomposition
   double      fEigenValues[3];    //Eigen values from SVD decomposition
   vector<vector<double> > fEigenVectors;      //The three principle axes
   double                  fAvePosition[3];    //Average position of hits fed to PCA
   double                  fAveHitDoca;        //Average doca of hits used in PCA
   unsigned long           fID;                //axis ID

   PCAxis();
   PCAxis(const PCAxis & );
   virtual ~PCAxis();

   ClassDef(PCAxis,13); // Generated by MakeProject.
};
} // namespace
#endif
