//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef recob__Wire_h
#define recob__Wire_h
namespace recob {
class Wire;
} // end of namespace.

#include "Rtypes.h"
#include "lar__sparse_vector_float_.h"

namespace recob {
class Wire {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fChannel;    //ID of the associated channel.
   Int_t        fView;       //View corresponding to the plane of this wire.
   lar::sparse_vector<float> fSignalROI;    //Signal on the channel as function of time tick.

   Wire();
   Wire(Wire && ) = default;
   Wire(const Wire & );
   virtual ~Wire();

   ClassDef(Wire,20); // Generated by MakeProject.
};
} // namespace
#endif
