//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef recob__PFParticle_h
#define recob__PFParticle_h
namespace recob {
class PFParticle;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace recob {
class PFParticle {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fPdgCode;    //A preliminary estimate of the PFParticle type using the PDG code
   unsigned long fSelf;       //Self reference
   unsigned long fParent;     //Index into PFParticle collection for parent
   vector<unsigned long> fDaughters;    //Vector of indices into PFParticle Collection for daughters

   PFParticle();
   PFParticle(const PFParticle & );
   virtual ~PFParticle();

   ClassDef(PFParticle,14); // Generated by MakeProject.
};
} // namespace
#endif
