//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef recob__Wire_h
#define recob__Wire_h
namespace recob {
class Wire;
} // end of namespace.

#include "Rtypes.h"
#include "lar__sparse_vector_float_.h"

namespace recob {
class Wire {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fChannel;    //ID of the associated channel.
   Int_t        fView;       //View corresponding to the plane of this wire.
   lar::sparse_vector<float> fSignalROI;    //Signal on the channel as function of time tick.

   Wire();
   Wire(const Wire & );
   virtual ~Wire();

   ClassDef(Wire,20); // Generated by MakeProject.
};
} // namespace
#endif
