//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef recob__PCAxis_h
#define recob__PCAxis_h
namespace recob {
class PCAxis;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;

namespace recob {
class PCAxis {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        fSvdOK;      //SVD Decomposition was successful
   int         fNumHitsUsed;    //Number of hits in the decomposition
   double      fEigenValues[3];    //Eigen values from SVD decomposition
   vector<vector<double> > fEigenVectors;      //The three principle axes
   double                  fAvePosition[3];    //Average position of hits fed to PCA
   double                  fAveHitDoca;        //Average doca of hits used in PCA
   unsigned long           fID;                //axis ID

   PCAxis();
   PCAxis(PCAxis && ) = default;
   PCAxis(const PCAxis & );
   virtual ~PCAxis();

   ClassDef(PCAxis,13); // Generated by MakeProject.
};
} // namespace
#endif
