//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef recob__Shower_h
#define recob__Shower_h
namespace recob {
class Shower;
} // end of namespace.

#include "Rtypes.h"
#include "TVector3.h"
#include "Riostream.h"
#include <vector>

namespace recob {
class Shower {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fID;         //
   TVector3    fDCosStart;    //direction cosines at start of shower
   TVector3    fSigmaDCosStart;    //uncertainty on initial direction cosines
   TVector3    fXYZstart;          //direction cosines at start of shower
   TVector3    fSigmaXYZstart;     //uncertainty on initial direction cosines
   vector<double> fTotalEnergy;       //Calculated Energy per each plane
   vector<double> fSigmaTotalEnergy;    //Calculated Energy per each plane
   vector<double> fdEdx;                //Calculated dE/dx per each plane
   vector<double> fSigmadEdx;           //Calculated dE/dx per each plane
   vector<double> fTotalMIPEnergy;      //Calculated Energy per each plane
   vector<double> fSigmaTotalMIPEnergy;    //Calculated Energy per each plane
   int            fBestPlane;              //
   double         fLength;                 //
   double         fOpenAngle;              //

   Shower();
   Shower(const Shower & );
   virtual ~Shower();

   ClassDef(Shower,15); // Generated by MakeProject.
};
} // namespace
#endif
