//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef recob__Hit_h
#define recob__Hit_h
namespace recob {
class Hit;
} // end of namespace.

#include "Rtypes.h"
#include "geo__WireID.h"

namespace recob {
class Hit {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fChannel;    //ID of the readout channel the hit was extracted from
   int          fStartTick;    //initial tdc tick for hit
   int          fEndTick;      //final tdc tick for hit
   float        fPeakTime;     //time of the signal peak, in tick units
   float        fSigmaPeakTime;    //uncertainty for the signal peak, in tick units
   float        fRMS;              //RMS of the hit shape, in tick units
   float        fPeakAmplitude;    //the estimated amplitude of the hit at its peak, in ADC units
   float        fSigmaPeakAmplitude;    //uncertainty on estimated amplitude of the hit at its peak, in ADC units
   float        fSummedADC;             //the sum of calibrated ADC counts of the hit
   float        fIntegral;              //the integral under the calibrated signal waveform of the hit, in tick x ADC units
   float        fSigmaIntegral;         //the uncertainty of integral under the calibrated signal waveform of the hit, in ADC units
   short        fMultiplicity;          //how many hits could this one be shared with
   short        fLocalIndex;            //index of this hit among the Multiplicity() hits in the signal window
   float        fGoodnessOfFit;         //how well do we believe we know this hit?
   int          fNDF;                   //degrees of freedom in the determination of the hit shape
   Int_t        fView;                  //view for the plane of the hit
   Int_t        fSignalType;            //signal type for the plane of the hit
   geo::WireID  fWireID;                //WireID for the hit (Cryostat, TPC, Plane, Wire)

   Hit();
   Hit(Hit && ) = default;
   Hit(const Hit & );
   virtual ~Hit();

   ClassDef(Hit,17); // Generated by MakeProject.
};
} // namespace
#endif
