//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef sim__AuxDetSimChannel_h
#define sim__AuxDetSimChannel_h
namespace sim {
class AuxDetSimChannel;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "sim__AuxDetIDE.h"

namespace sim {
class AuxDetSimChannel {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fAuxDetID;    //geo->AuxDet(auxDetID), integer used to retrieve AuxDetGeo objec
   unsigned int fAuxDetSensitiveID;    //integer used to retrieve AuxDetSensitiveGeo object
   vector<sim::AuxDetIDE> fAuxDetIDEs;           //one sim::AuxDetIDE for each G4 track id

   AuxDetSimChannel();
   AuxDetSimChannel(AuxDetSimChannel && ) = default;
   AuxDetSimChannel(const AuxDetSimChannel & );
   virtual ~AuxDetSimChannel();

   ClassDef(AuxDetSimChannel,13); // Generated by MakeProject.
};
} // namespace
#endif
