//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef sim__SimChannel_h
#define sim__SimChannel_h
namespace sim {
class SimChannel;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include <utility>
namespace std {} using namespace std;
#include "sim__IDE.h"

namespace sim {
class SimChannel {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fChannel;    //readout channel where electrons are collected
   vector<pair<unsigned short,vector<sim::IDE> > > fTDCIDEs;    //list of energy deposits for each TDC with signal

   SimChannel();
   SimChannel(SimChannel && ) = default;
   SimChannel(const SimChannel & );
   virtual ~SimChannel();

   ClassDef(SimChannel,16); // Generated by MakeProject.
};
} // namespace
#ifdef __MAKECINT__
#pragma link C++ class pair<unsigned short,vector<sim::IDE> >+;
#endif
#endif
