//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef sim__IDE_h
#define sim__IDE_h
namespace sim {
class IDE;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class IDE {

public:
// Nested classes declaration.

public:
// Data Members.
   int         trackID;     //Geant4 supplied track ID
   float       numElectrons;    //number of electrons at the readout for this track ID and time
   float       energy;          //energy deposited by ionization by this track ID and time [MeV]
   float       x;               //x position of ionization [cm]
   float       y;               //y position of ionization [cm]
   float       z;               //z position of ionization [cm]

   IDE();
   //   IDE(IDE && ) = default;
   IDE(const IDE & );
   virtual ~IDE();

   ClassDef(IDE,12); // Generated by MakeProject.
};
} // namespace
#endif
