//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef sim__AuxDetSimChannel_h
#define sim__AuxDetSimChannel_h
namespace sim {
class AuxDetSimChannel;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "sim__AuxDetIDE.h"

namespace sim {
class AuxDetSimChannel {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fAuxDetID;    //geo->AuxDet(auxDetID), integer used to retrieve AuxDetGeo objec
   unsigned int fAuxDetSensitiveID;    //integer used to retrieve AuxDetSensitiveGeo object
   vector<sim::AuxDetIDE> fAuxDetIDEs;           //one sim::AuxDetIDE for each G4 track id

   AuxDetSimChannel();
   AuxDetSimChannel(const AuxDetSimChannel & );
   virtual ~AuxDetSimChannel();

   ClassDef(AuxDetSimChannel,13); // Generated by MakeProject.
};
} // namespace
#endif
