//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef sim__GeneratedParticleInfo_h
#define sim__GeneratedParticleInfo_h
namespace sim {
class GeneratedParticleInfo;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class GeneratedParticleInfo {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long fGeneratedParticleIndex;    //

   GeneratedParticleInfo();
   GeneratedParticleInfo(const GeneratedParticleInfo & );
   virtual ~GeneratedParticleInfo();

};
} // namespace
#endif
