//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef sim__OpDetDivRec_h
#define sim__OpDetDivRec_h
namespace sim {
class OpDetDivRec;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "sim__OpDet_Time_Chans.h"

namespace sim {
class OpDetDivRec {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fOpDetNum;    //Move this to be private.
   vector<sim::OpDet_Time_Chans> time_chans;    //Move this to private //This must be filled with emplace to keep it sorted.

   OpDetDivRec();
   OpDetDivRec(OpDetDivRec && ) = default;
   OpDetDivRec(const OpDetDivRec & );
   virtual ~OpDetDivRec();

   ClassDef(OpDetDivRec,14); // Generated by MakeProject.
};
} // namespace
#endif
