//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef sim__OpDet_Time_Chans_h
#define sim__OpDet_Time_Chans_h
namespace sim {
class OpDet_Time_Chans;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "sim__Chan_Phot.h"

namespace sim {
class OpDet_Time_Chans {

public:
// Nested classes declaration.

public:
// Data Members.
   double      time;        //
   vector<sim::Chan_Phot> phots;       //

   OpDet_Time_Chans();
   OpDet_Time_Chans(OpDet_Time_Chans && ) = default;
   OpDet_Time_Chans(const OpDet_Time_Chans & );
   virtual ~OpDet_Time_Chans();

};
} // namespace
#endif
