//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef sim__ProtoDUNEBeamInstrument_h
#define sim__ProtoDUNEBeamInstrument_h
namespace sim {
class ProtoDUNEBeamInstrument;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace sim {
class ProtoDUNEBeamInstrument {

public:
// Nested classes declaration.

public:
// Data Members.
   string      fInstrumentName;    //
   float       fX;                 //
   float       fY;                 //
   float       fZ;                 //
   float       fT;                 //
   float       fPx;                //
   float       fPy;                //
   float       fPz;                //
   int         fPDGid;             //
   int         fEventID;           //
   int         fTrackID;           //
   float       fSmearedVar1;       //
   float       fSmearedVar2;       //
   float       fResolution;        //

   ProtoDUNEBeamInstrument();
   ProtoDUNEBeamInstrument(ProtoDUNEBeamInstrument && ) = default;
   ProtoDUNEBeamInstrument(const ProtoDUNEBeamInstrument & );
   virtual ~ProtoDUNEBeamInstrument();

   ClassDef(ProtoDUNEBeamInstrument,11); // Generated by MakeProject.
};
} // namespace
#endif
