//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef sim__AuxDetIDE_h
#define sim__AuxDetIDE_h
namespace sim {
class AuxDetIDE;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class AuxDetIDE {

public:
// Nested classes declaration.

public:
// Data Members.
   int         trackID;     //Geant4 supplied track ID
   float       energyDeposited;    //total energy deposited for this track ID and time
   float       entryX;             //Entry position X of particle
   float       entryY;             //Entry position Y of particle
   float       entryZ;             //Entry position Z of particle
   float       entryT;             //Entry time of particle
   float       exitX;              //Exit position X of particle
   float       exitY;              //Exit position Y of particle
   float       exitZ;              //Exit position Z of particle
   float       exitT;              //Exit time of particle
   float       exitMomentumX;      //Exit X-Momentum of particle
   float       exitMomentumY;      //Exit Y-Momentum of particle
   float       exitMomentumZ;      //Exit Z-Momentum of particle

   AuxDetIDE();
   AuxDetIDE(AuxDetIDE && ) = default;
   AuxDetIDE(const AuxDetIDE & );
   virtual ~AuxDetIDE();

   ClassDef(AuxDetIDE,11); // Generated by MakeProject.
};
} // namespace
#endif
