//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef sim__SDP_h
#define sim__SDP_h
namespace sim {
class SDP;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class SDP {

public:
// Nested classes declaration.

public:
// Data Members.
   int         trackID;     //Geant4 supplied track ID
   float       numPhotons;    //number of photons at the optical detector for this track ID and time
   float       energy;        //energy deposited by ionization
   float       x;             //x position of ionization [cm]
   float       y;             //y position of ionization [cm]
   float       z;             //z position of ionization [cm]

   SDP();
   SDP(const SDP & );
   virtual ~SDP();

};
} // namespace
#endif
