//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Feb 13 18:14:53 2020 by ROOT version 6.16/00)
//      from the StreamerInfo in file ../PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23473772_0_452d9f89-a2a1-4680-ab72-853a3261da5d.root
//////////////////////////////////////////////////////////


#ifndef sim__ProtoDUNEBeamInstrument_h
#define sim__ProtoDUNEBeamInstrument_h
namespace sim {
class ProtoDUNEBeamInstrument;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace sim {
class ProtoDUNEBeamInstrument {

public:
// Nested classes declaration.

public:
// Data Members.
   string      fInstrumentName;    //
   float       fX;                 //
   float       fY;                 //
   float       fZ;                 //
   float       fT;                 //
   float       fPx;                //
   float       fPy;                //
   float       fPz;                //
   int         fPDGid;             //
   int         fEventID;           //
   int         fTrackID;           //
   float       fSmearedVar1;       //
   float       fSmearedVar2;       //
   float       fResolution;        //

   ProtoDUNEBeamInstrument();
   ProtoDUNEBeamInstrument(const ProtoDUNEBeamInstrument & );
   virtual ~ProtoDUNEBeamInstrument();

   ClassDef(ProtoDUNEBeamInstrument,11); // Generated by MakeProject.
};
} // namespace
#endif
