//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:05 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef simb__MCParticle_h
#define simb__MCParticle_h
namespace simb {
class MCParticle;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include "simb__MCTrajectory.h"
#include "TVector3.h"
#include <set>
#include "TLorentzVector.h"

namespace simb {
class MCParticle {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fstatus;     //Status code from generator, geant, etc
   int         ftrackId;    //TrackId
   int         fpdgCode;    //PDG code
   int         fmother;     //Mother
   string      fprocess;    //Detector-simulation physics process that created the particle
   string      fendprocess;    //end process for the particle
   simb::MCTrajectory ftrajectory;    //particle trajectory (position,momentum)
   double             fmass;          //Mass; from PDG unless overridden Should be in GeV
   TVector3           fpolarization;    //Polarization
   std::set<int>      fdaughters;       //Sorted list of daughters of this particle.
   double             fWeight;          //Assigned weight to this particle for MC tests
   TLorentzVector     fGvtx;            //Vertex needed by generater (genie) to rebuild
   int                frescatter;       //rescatter code

   MCParticle();
   MCParticle(MCParticle && ) = default;
   MCParticle(const MCParticle & );
   virtual ~MCParticle();

   ClassDef(MCParticle,19); // Generated by MakeProject.
};
} // namespace
#endif
