//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef simb__MCGeneratorInfo_h
#define simb__MCGeneratorInfo_h
namespace simb {
class MCGeneratorInfo;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include <unordered_map>

namespace simb {
class MCGeneratorInfo {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       generator;    //event generator that generated this event
   string      generatorVersion;    //event generator version
   unordered_map<string,string> generatorConfig;     //free-form field that can be used to keep track of generator configuration (e.g. GENIE tune)

   MCGeneratorInfo();
   MCGeneratorInfo(MCGeneratorInfo && ) = default;
   MCGeneratorInfo(const MCGeneratorInfo & );
   virtual ~MCGeneratorInfo();

   ClassDef(MCGeneratorInfo,11); // Generated by MakeProject.
};
} // namespace
#endif
