//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef util__flags__BitMask_unsigned_int__h
#define util__flags__BitMask_unsigned_int__h
namespace util {
namespace flags {
template <typename T0> class BitMask;
template <> class BitMask<unsigned int>;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "util__flags__Bits_t_unsigned_int_.h"

namespace util {
namespace flags {
template <typename T0> class BitMask;
template <> class BitMask<unsigned int> {

public:
// Nested classes declaration.

public:
// Data Members.
   util::flags::Bits_t<unsigned int> values;      //Storage of value bits.
   util::flags::Bits_t<unsigned int> presence;    //Storage of definition bits.

   BitMask();
   BitMask(BitMask && ) = default;
   BitMask(const BitMask & );
   virtual ~BitMask();

};
} // namespace
} // namespace
#endif
