//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Apr 24 09:37:06 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /pnfs/dune/archive/sam_managed_users/calcuttj/data/5/c/5/d/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23503706_0_124d8226-6d53-4dbc-af94-340521eab19b_pma.root
//////////////////////////////////////////////////////////


#ifndef util__flags__FlagSet_32_unsigned_int__h
#define util__flags__FlagSet_32_unsigned_int__h
namespace util {
namespace flags {
template <int T0, typename T1> class FlagSet;
template <> class FlagSet<32,unsigned int>;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "util__flags__BitMask_unsigned_int_.h"

namespace util {
namespace flags {
template <int T0, typename T1> class FlagSet;
template <> class FlagSet<32,unsigned int> : public util::flags::BitMask<unsigned int> {

public:
// Nested classes declaration.

public:
// Data Members.

   FlagSet();
   FlagSet(FlagSet && ) = default;
   FlagSet(const FlagSet & );
   virtual ~FlagSet();

};
} // namespace
} // namespace
#endif
