//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef anab__T0_h
#define anab__T0_h
namespace anab {
class T0;
} // end of namespace.

#include "Rtypes.h"

namespace anab {
class T0 {

public:
// Nested classes declaration.

public:
// Data Members.
   double      fTime;       //Time in ns
   unsigned int fTriggerType;    //Type of trigger used. 0 - Muon Counters, 1 - Photon Detectors, 2 - Monte Carlo Truth
   int          fTriggerBits;    //An identifier for the Muon track / Flash / MCParticle used in matching.
   int          fID;             //Current size of T0 data product.
   double       fTriggerConfidence;    //Confidence with which this T0 is known.

   T0();
   T0(const T0 & );
   virtual ~T0();

   ClassDef(T0,16); // Generated by MakeProject.
};
} // namespace
#endif
