//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef anab__Calorimetry_h
#define anab__Calorimetry_h
namespace anab {
class Calorimetry;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "Math/GenVector/PositionVector3D.h"
#include "Math/GenVector/Cartesian3D.h"
#include "Math/GenVector/CoordinateSystemTags.h"
#include "geo__PlaneID.h"

namespace anab {
class Calorimetry {

public:
// Nested classes declaration.

public:
// Data Members.
   float       fKineticEnergy;    //determined kinetic energy
   vector<float> fdEdx;             //dE/dx, should be same size as fResidualRange
   vector<float> fdQdx;             //dQ/dx
   vector<float> fResidualRange;    //range from end of track
   vector<float> fDeadWireResR;     //dead wire residual range, collection plane
   float         fRange;            //total range of track
   vector<float> fTrkPitch;         //track pitch on collection plane
   vector<ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::GlobalCoordinateSystemTag> > fXYZ;              //coordinates of space points; for a discussion on the object type for coordinates see recob::tracking::Coord_t.
   vector<unsigned long>                                                                                            fTpIndices;        //indices of original trajectory points on track
   geo::PlaneID                                                                                                     fPlaneID;          //

   Calorimetry();
   Calorimetry(const Calorimetry & );
   virtual ~Calorimetry();

   ClassDef(Calorimetry,18); // Generated by MakeProject.
};
} // namespace
#endif
