//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef anab__CosmicTag_h
#define anab__CosmicTag_h
namespace anab {
class CosmicTag;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace anab {
class CosmicTag {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<float> endPt1;      //x,y,z assuming t_0 = t_beam
   vector<float> endPt2;      //x,y,z assuming t_0 = t_beam
   float         fCosmicScore;    //-1 means very likely neutrino,
   Int_t         fCosmicType;     //

   CosmicTag();
   CosmicTag(const CosmicTag & );
   virtual ~CosmicTag();

   ClassDef(CosmicTag,4); // Generated by MakeProject.
};
} // namespace
#endif
