//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef art__ProductProvenance_h
#define art__ProductProvenance_h
namespace art {
class ProductProvenance;
} // end of namespace.

#include "Rtypes.h"
#include "art__ProductID.h"
#include "art__Hash_5_.h"
#include "art__Transient_art__ProductProvenance__Transients_.h"
namespace art {
#ifndef art__ProductProvenance_h
#define art__ProductProvenance_h
enum ProductProvenance::Transients { kDefault_ProductProvenance::Transients };
#endif
} // end of namespace.

namespace art {
class ProductProvenance {

public:
// Nested classes forward declaration.
enum Transients { kDefault_Transients };

public:
// Nested classes declaration.

public:
// Data Members.
   art::ProductID productID_;    //
   unsigned char  productStatus_;    //
   art::Hash<5>   parentageID_;      //
   art::Transient<art::ProductProvenance::Transients> transients_;       //

   ProductProvenance();
   ProductProvenance(const ProductProvenance & );
   virtual ~ProductProvenance();

   ClassDef(ProductProvenance,12); // Generated by MakeProject.
};
} // namespace
#endif
