//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef art__RunID_h
#define art__RunID_h
namespace art {
class RunID;
} // end of namespace.

#include "Rtypes.h"

namespace art {
class RunID {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int run_;        //

   RunID();
   RunID(const RunID & );
   virtual ~RunID();

   ClassDef(RunID,11); // Generated by MakeProject.
};
} // namespace
#endif
