//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef art__BranchChildren_h
#define art__BranchChildren_h
namespace art {
class BranchChildren;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <map>
#include "art__ProductID.h"
#include <set>
namespace std {} using namespace std;
#ifdef __MAKECINT__
#pragma link C++ class pair<art::ProductID,vector<art::ProductID> >+;
#endif

namespace art {
class BranchChildren {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<std::pair<art::ProductID,std::vector<art::ProductID> > > childLookup_;    //

   BranchChildren();
   BranchChildren(const BranchChildren & );
   virtual ~BranchChildren();

   ClassDef(BranchChildren,12); // Generated by MakeProject.
};
} // namespace
#endif
