//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef art__SubRunAuxiliary_h
#define art__SubRunAuxiliary_h
namespace art {
class SubRunAuxiliary;
} // end of namespace.

#include "Rtypes.h"
#include "art__Hash_2_.h"
#include "art__SubRunID.h"
#include "art__Timestamp.h"

namespace art {
class SubRunAuxiliary {

public:
// Nested classes declaration.

public:
// Data Members.
   art::Hash<2> processHistoryID_;    //
   unsigned int rangeSetID_;          //
   art::SubRunID id_;                  //
   art::Timestamp beginTime_;           //
   art::Timestamp endTime_;             //

   SubRunAuxiliary();
   SubRunAuxiliary(const SubRunAuxiliary & );
   virtual ~SubRunAuxiliary();

   ClassDef(SubRunAuxiliary,12); // Generated by MakeProject.
};
} // namespace
#endif
