//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef CRT__Trigger_h
#define CRT__Trigger_h
namespace CRT {
class Trigger;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "CRT__Hit.h"

namespace CRT {
class Trigger {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short fChannel;    //Mapping to CRT module that was Triggered.  Index into the Geometry service's array of AuxDetGeos
   ULong64_t      fTimestamp;    //Timestamp when this Trigger occurred.  First 32 bits are Linux time since epoch; last 32 bits are time in
   vector<CRT::Hit> fHits;         //All activity in CRT strips within this module when it was read out

   Trigger();
   Trigger(const Trigger & );
   virtual ~Trigger();

   ClassDef(Trigger,11); // Generated by MakeProject.
};
} // namespace
#endif
