//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef CRT__Hit_h
#define CRT__Hit_h
namespace CRT {
class Hit;
} // end of namespace.

#include "Rtypes.h"

namespace CRT {
class Hit {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long fChannel;    //The index of the AuxDetSensitiveGeo that represents this strip in a CRT module
   short         fADC;        //Baseline-subtracted Analog to Digital Converter value at time when this hit was read out.

   Hit();
   Hit(const Hit & );
   virtual ~Hit();

   ClassDef(Hit,11); // Generated by MakeProject.
};
} // namespace
#endif
