//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef raw__RawDigit_h
#define raw__RawDigit_h
namespace raw {
class RawDigit;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace raw {
class RawDigit {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<short> fADC;        //ADC readout per tick, before pedestal subtraction
   unsigned int  fChannel;    //channel number in the readout
   unsigned short fSamples;    //number of ticks of the clock
   float          fPedestal;    //pedestal for this channel
   float          fSigma;       //sigma of the pedestal counts for this channel
   Int_t          fCompression;    //compression scheme used for the ADC vector

   RawDigit();
   RawDigit(const RawDigit & );
   virtual ~RawDigit();

   ClassDef(RawDigit,15); // Generated by MakeProject.
};
} // namespace
#endif
