//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef recob__Track_h
#define recob__Track_h
namespace recob {
class Track;
} // end of namespace.

#include "Rtypes.h"
#include "recob__TrackTrajectory.h"
#include "Math/SMatrix.h"
#include "Math/MatrixRepresentationsStatic.h"

namespace recob {
class Track {

public:
// Nested classes declaration.

public:
// Data Members.
   recob::TrackTrajectory fTraj;       //Stored trajectory data member
   int                    fPId;        //Particle ID hypothesis used in the fit (if any)
   float                  fChi2;       //Fit chi2
   int                    fNdof;       //Number of degrees of freedom of the fit
   ROOT::Math::SMatrix<Double32_t,5,5,ROOT::Math::MatRepSym<Double32_t,5> > fCovVertex;    //Covariance matrix (local 5D representation) at start point (vertex)
   ROOT::Math::SMatrix<Double32_t,5,5,ROOT::Math::MatRepSym<Double32_t,5> > fCovEnd;       //Covariance matrix (local 5D representation) at end point
   int                                                                      fID;           //track's ID

   Track();
   Track(const Track & );
   virtual ~Track();

   ClassDef(Track,18); // Generated by MakeProject.
};
} // namespace
#endif
