//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef recob__PFParticle_h
#define recob__PFParticle_h
namespace recob {
class PFParticle;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace recob {
class PFParticle {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fPdgCode;    //A preliminary estimate of the PFParticle type using the PDG code
   unsigned long fSelf;       //Self reference
   unsigned long fParent;     //Index into PFParticle collection for parent
   vector<unsigned long> fDaughters;    //Vector of indices into PFParticle Collection for daughters

   PFParticle();
   PFParticle(const PFParticle & );
   virtual ~PFParticle();

   ClassDef(PFParticle,14); // Generated by MakeProject.
};
} // namespace
#endif
