//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef sim__OpDet_Time_Chans_h
#define sim__OpDet_Time_Chans_h
namespace sim {
class OpDet_Time_Chans;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "sim__Chan_Phot.h"

namespace sim {
class OpDet_Time_Chans {

public:
// Nested classes declaration.

public:
// Data Members.
   double      time;        //
   vector<sim::Chan_Phot> phots;       //

   OpDet_Time_Chans();
   OpDet_Time_Chans(const OpDet_Time_Chans & );
   virtual ~OpDet_Time_Chans();

};
} // namespace
#endif
