//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef sim__OpDetBacktrackerRecord_h
#define sim__OpDetBacktrackerRecord_h
namespace sim {
class OpDetBacktrackerRecord;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include <utility>
namespace std {} using namespace std;
#include "sim__SDP.h"

namespace sim {
class OpDetBacktrackerRecord {

public:
// Nested classes declaration.

public:
// Data Members.
   int         iOpDetNum;    //OpticalDetector where the photons were detected
   vector<pair<double,vector<sim::SDP> > > timePDclockSDPs;    //list of energy deposits for each timePDclock with signal

   OpDetBacktrackerRecord();
   OpDetBacktrackerRecord(const OpDetBacktrackerRecord & );
   virtual ~OpDetBacktrackerRecord();

   ClassDef(OpDetBacktrackerRecord,12); // Generated by MakeProject.
};
} // namespace
#ifdef __MAKECINT__
#pragma link C++ class pair<double,vector<sim::SDP> >+;
#endif
#endif
