//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef sim__IDE_h
#define sim__IDE_h
namespace sim {
class IDE;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class IDE {

public:
// Nested classes declaration.

public:
// Data Members.
   int         trackID;     //Geant4 supplied track ID
   float       numElectrons;    //number of electrons at the readout for this track ID and time
   float       energy;          //energy deposited by ionization by this track ID and time [MeV]
   float       x;               //x position of ionization [cm]
   float       y;               //y position of ionization [cm]
   float       z;               //z position of ionization [cm]

   IDE();
   IDE(const IDE & );
   virtual ~IDE();

   ClassDef(IDE,12); // Generated by MakeProject.
};
} // namespace
#endif
