//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef sim__AuxDetIDE_h
#define sim__AuxDetIDE_h
namespace sim {
class AuxDetIDE;
} // end of namespace.

#include "Rtypes.h"

namespace sim {
class AuxDetIDE {

public:
// Nested classes declaration.

public:
// Data Members.
   int         trackID;     //Geant4 supplied track ID
   float       energyDeposited;    //total energy deposited for this track ID and time
   float       entryX;             //Entry position X of particle
   float       entryY;             //Entry position Y of particle
   float       entryZ;             //Entry position Z of particle
   float       entryT;             //Entry time of particle
   float       exitX;              //Exit position X of particle
   float       exitY;              //Exit position Y of particle
   float       exitZ;              //Exit position Z of particle
   float       exitT;              //Exit time of particle
   float       exitMomentumX;      //Exit X-Momentum of particle
   float       exitMomentumY;      //Exit Y-Momentum of particle
   float       exitMomentumZ;      //Exit Z-Momentum of particle

   AuxDetIDE();
   AuxDetIDE(const AuxDetIDE & );
   virtual ~AuxDetIDE();

   ClassDef(AuxDetIDE,11); // Generated by MakeProject.
};
} // namespace
#endif
