//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef simb__MCParticle_h
#define simb__MCParticle_h
namespace simb {
class MCParticle;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include "simb__MCTrajectory.h"
#include "TVector3.h"
#include <set>
#include "TLorentzVector.h"

namespace simb {
class MCParticle {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fstatus;     //Status code from generator, geant, etc
   int         ftrackId;    //TrackId
   int         fpdgCode;    //PDG code
   int         fmother;     //Mother
   string      fprocess;    //Detector-simulation physics process that created the particle
   string      fendprocess;    //end process for the particle
   simb::MCTrajectory ftrajectory;    //particle trajectory (position,momentum)
   double             fmass;          //Mass; from PDG unless overridden Should be in GeV
   TVector3           fpolarization;    //Polarization
   std::set<int>      fdaughters;       //Sorted list of daughters of this particle.
   double             fWeight;          //Assigned weight to this particle for MC tests
   TLorentzVector     fGvtx;            //Vertex needed by generater (genie) to rebuild
   int                frescatter;       //rescatter code

   MCParticle();
   MCParticle(const MCParticle & );
   virtual ~MCParticle();

   ClassDef(MCParticle,19); // Generated by MakeProject.
};
} // namespace
#endif
