//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef simb__MCNeutrino_h
#define simb__MCNeutrino_h
namespace simb {
class MCNeutrino;
} // end of namespace.

#include "Rtypes.h"
#include "simb__MCParticle.h"

namespace simb {
class MCNeutrino {

public:
// Nested classes declaration.

public:
// Data Members.
   simb::MCParticle fNu;         //the incoming neutrino
   simb::MCParticle fLepton;     //the outgoing lepton
   int              fMode;       //Interaction mode (QE/1-pi/DIS...) see enum list
   int              fInteractionType;    //More detailed interaction type, see enum list below kNuanceOffset
   int              fCCNC;               //CC or NC interaction? see enum list
   int              fTarget;             //Nuclear target, as PDG code
   int              fHitNuc;             //Hit nucleon (2212 (proton) or 2112 (neutron))
   int              fHitQuark;           //For DIS events only, as PDG code
   double           fW;                  //Hadronic invariant mass, in GeV
   double           fX;                  //Bjorken x=Q^2/(2M*(E_neutrino-E_lepton)), unitless
   double           fY;                  //Inelasticity y=1-(E_lepton/E_neutrino), unitless
   double           fQSqr;               //Momentum transfer Q^2, in GeV^2

   MCNeutrino();
   MCNeutrino(const MCNeutrino & );
   virtual ~MCNeutrino();

   ClassDef(MCNeutrino,11); // Generated by MakeProject.
};
} // namespace
#endif
