//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef sumdata__RunData_h
#define sumdata__RunData_h
namespace sumdata {
class RunData;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace sumdata {
class RunData {

public:
// Nested classes declaration.

public:
// Data Members.
   string      fDetName;    //Detector name.

   RunData();
   RunData(const RunData & );
   virtual ~RunData();

   ClassDef(RunData,14); // Generated by MakeProject.
};
} // namespace
#endif
