//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun  4 02:53:16 2019 by ROOT version 6.12/06)
//      from the StreamerInfo in file /pnfs/dune/scratch/users/tjyang/v08_21_00/reco/mcc12_protodune_beam_p1GeV_cosmics_12ms_test/19285494_84/mcc12_protodune_beam_p1GeV_cosmics_12ms_test_84_20190601T145951_reco0.root
//////////////////////////////////////////////////////////


#ifndef util__flags__BitMask_unsigned_int__h
#define util__flags__BitMask_unsigned_int__h
namespace util {
namespace flags {
template <typename T0> class BitMask;
template <> class BitMask<unsigned int>;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "util__flags__Bits_t_unsigned_int_.h"

namespace util {
namespace flags {
template <typename T0> class BitMask;
template <> class BitMask<unsigned int> {

public:
// Nested classes declaration.

public:
// Data Members.
   util::flags::Bits_t<unsigned int> values;      //Storage of value bits.
   util::flags::Bits_t<unsigned int> presence;    //Storage of definition bits.

   BitMask();
   BitMask(const BitMask & );
   virtual ~BitMask();

};
} // namespace
} // namespace
#endif
